package com.feihua.framework.statistic.dto;

import feihua.jdbc.api.pojo.BaseDbDto;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table statistic_user_area_count
 *
 * @mbg.generated 2019-04-25 11:13:39
*/
public class StatisticUserAreaCountDto extends BaseDbDto<String> {
    private String id;

    private String areaId;

    private String areaName;

    private String batchNo;

    private Integer allNum;

    private Integer maleNum;

    private Integer femaleNum;

    private Integer genderOtherNum;

    private Integer onlineAllNum;

    private Integer onlineMaleNum;

    private Integer onlineFemaleNum;

    private Integer onlineGenderOtherNum;

    private String longitude;

    private String latitude;

    private String dataUserId;

    private String dataOfficeId;

    private String dataType;

    private String dataAreaId;

    private String delFlag;

    private Date createAt;

    private String createBy;

    private Date updateAt;

    private String updateBy;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public Integer getAllNum() {
        return allNum;
    }

    public void setAllNum(Integer allNum) {
        this.allNum = allNum;
    }

    public Integer getMaleNum() {
        return maleNum;
    }

    public void setMaleNum(Integer maleNum) {
        this.maleNum = maleNum;
    }

    public Integer getFemaleNum() {
        return femaleNum;
    }

    public void setFemaleNum(Integer femaleNum) {
        this.femaleNum = femaleNum;
    }

    public Integer getGenderOtherNum() {
        return genderOtherNum;
    }

    public void setGenderOtherNum(Integer genderOtherNum) {
        this.genderOtherNum = genderOtherNum;
    }

    public Integer getOnlineAllNum() {
        return onlineAllNum;
    }

    public void setOnlineAllNum(Integer onlineAllNum) {
        this.onlineAllNum = onlineAllNum;
    }

    public Integer getOnlineMaleNum() {
        return onlineMaleNum;
    }

    public void setOnlineMaleNum(Integer onlineMaleNum) {
        this.onlineMaleNum = onlineMaleNum;
    }

    public Integer getOnlineFemaleNum() {
        return onlineFemaleNum;
    }

    public void setOnlineFemaleNum(Integer onlineFemaleNum) {
        this.onlineFemaleNum = onlineFemaleNum;
    }

    public Integer getOnlineGenderOtherNum() {
        return onlineGenderOtherNum;
    }

    public void setOnlineGenderOtherNum(Integer onlineGenderOtherNum) {
        this.onlineGenderOtherNum = onlineGenderOtherNum;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getDataUserId() {
        return dataUserId;
    }

    public void setDataUserId(String dataUserId) {
        this.dataUserId = dataUserId;
    }

    public String getDataOfficeId() {
        return dataOfficeId;
    }

    public void setDataOfficeId(String dataOfficeId) {
        this.dataOfficeId = dataOfficeId;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getDataAreaId() {
        return dataAreaId;
    }

    public void setDataAreaId(String dataAreaId) {
        this.dataAreaId = dataAreaId;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public Date getCreateAt() {
        return createAt;
    }

    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Date getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
}