package com.feihua.framework.base.modules.function.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-20 09:39:08
 * Database Table Remarks:
 *   功能资源表
 *
 * This class corresponds to the database table base_function_resource
 * @mbg.generated do_not_delete_during_merge 2019-06-20 09:39:08
*/
public class BaseFunctionResourcePo extends feihua.jdbc.api.pojo.BaseTreePo<String> {
    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource.NAME
     *
     * @mbg.generated 2019-06-20 09:39:08
     */
    private String name;

    /**
     * Database Column Remarks:
     *   资源编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource.CODE
     *
     * @mbg.generated 2019-06-20 09:39:08
     */
    private String code;

    /**
     * Database Column Remarks:
     *   图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource.ICON
     *
     * @mbg.generated 2019-06-20 09:39:08
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   是否显示,N=不显示，Y=显示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource.IS_SHOW
     *
     * @mbg.generated 2019-06-20 09:39:08
     */
    private String isShow;

    /**
     * Database Column Remarks:
     *   资源URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource.URL
     *
     * @mbg.generated 2019-06-20 09:39:08
     */
    private String url;

    /**
     * Database Column Remarks:
     *   权限标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource.PERMISSIONS
     *
     * @mbg.generated 2019-06-20 09:39:08
     */
    private String permissions;

    /**
     * Database Column Remarks:
     *   类型,page=页面，url=接口，group=功能组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource.TYPE
     *
     * @mbg.generated 2019-06-20 09:39:08
     */
    private String type;

    /**
     * Database Column Remarks:
     *   顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource.SEQUENCE
     *
     * @mbg.generated 2019-06-20 09:39:08
     */
    private Integer sequence;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getIsShow() {
        return isShow;
    }

    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPermissions() {
        return permissions;
    }

    public void setPermissions(String permissions) {
        this.permissions = permissions;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public com.feihua.framework.base.modules.function.api.ApiBaseFunctionResourcePoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.base.modules.function.api.ApiBaseFunctionResourcePoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", icon=").append(icon);
        sb.append(", isShow=").append(isShow);
        sb.append(", url=").append(url);
        sb.append(", permissions=").append(permissions);
        sb.append(", type=").append(type);
        sb.append(", sequence=").append(sequence);
        sb.append("]");
        return sb.toString();
    }
}