package com.feihua.framework.base.modules.function.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-03-19 14:24:58
 *
 * This class corresponds to the database table base_function_resource_data_scope_define_self
 * @mbg.generated do_not_delete_during_merge 2018-03-19 14:24:58
*/
public class BaseFunctionResourceDataScopeDefineSelfPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   功能数据范围定义id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource_data_scope_define_self.FUNCTION_RESOURCE_DATA_SCOPE_DEFINE_ID
     *
     * @mbg.generated 2018-03-19 14:24:58
     */
    private String functionResourceDataScopeDefineId;

    /**
     * Database Column Remarks:
     *   功能资源id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_function_resource_data_scope_define_self.FUNCTION_RESOURCE_ID
     *
     * @mbg.generated 2018-03-19 14:24:58
     */
    private String functionResourceId;

    public String getFunctionResourceDataScopeDefineId() {
        return functionResourceDataScopeDefineId;
    }

    public void setFunctionResourceDataScopeDefineId(String functionResourceDataScopeDefineId) {
        this.functionResourceDataScopeDefineId = functionResourceDataScopeDefineId;
    }

    public String getFunctionResourceId() {
        return functionResourceId;
    }

    public void setFunctionResourceId(String functionResourceId) {
        this.functionResourceId = functionResourceId;
    }

    public com.feihua.framework.base.modules.function.api.ApiBaseFunctionResourceDataScopeDefineSelfPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.base.modules.function.api.ApiBaseFunctionResourceDataScopeDefineSelfPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", functionResourceDataScopeDefineId=").append(functionResourceDataScopeDefineId);
        sb.append(", functionResourceId=").append(functionResourceId);
        sb.append("]");
        return sb.toString();
    }
}