package com.feihua.framework.cms.impl;

import com.feihua.framework.cms.api.ApiCmsQuestionOptionsPoService;
import com.feihua.framework.cms.dto.CmsQuestionOptionsDto;
import com.feihua.framework.cms.po.CmsQuestionOptionsPo;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-01-17 14:03:09
 */
@Service
public class ApiCmsQuestionOptionsPoServiceImpl extends ApiBaseServiceImpl<CmsQuestionOptionsPo, CmsQuestionOptionsDto, String> implements ApiCmsQuestionOptionsPoService {
    @Autowired
    com.feihua.framework.cms.mapper.CmsQuestionOptionsPoMapper CmsQuestionOptionsPoMapper;

    public ApiCmsQuestionOptionsPoServiceImpl() {
        super(CmsQuestionOptionsDto.class);
    }

    @Override
    public PageResultDto<CmsQuestionOptionsDto> searchCmsQuestionOptionssDsf(com.feihua.framework.cms.dto.SearchCmsQuestionOptionssConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.feihua.framework.cms.dto.CmsQuestionOptionsDto> list = this.wrapDtos(CmsQuestionOptionsPoMapper.searchCmsQuestionOptionss(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }

    @Override
    public CmsQuestionOptionsDto wrapDto(CmsQuestionOptionsPo po) {
        if (po == null) { return null; }
        CmsQuestionOptionsDto dto = new CmsQuestionOptionsDto();
        dto.setId(po.getId());
        dto.setQuestionId(po.getQuestionId());
        dto.setName(po.getName());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}