package com.feihua.framework.cms.impl;

import com.feihua.framework.cms.api.ApiCmsContentCommentPoService;
import com.feihua.framework.cms.dto.CmsContentCommentDto;
import com.feihua.framework.cms.po.CmsContentCommentPo;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-06 16:08:26
 */
@Service
public class ApiCmsContentCommentPoServiceImpl extends ApiBaseServiceImpl<CmsContentCommentPo, CmsContentCommentDto, String> implements ApiCmsContentCommentPoService {
    @Autowired
    com.feihua.framework.cms.mapper.CmsContentCommentPoMapper CmsContentCommentPoMapper;

    public ApiCmsContentCommentPoServiceImpl() {
        super(CmsContentCommentDto.class);
    }

    @Override
    public PageResultDto<CmsContentCommentDto> searchCmsContentCommentsDsf(com.feihua.framework.cms.dto.SearchCmsContentCommentsConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.feihua.framework.cms.dto.CmsContentCommentDto> list = this.wrapDtos(CmsContentCommentPoMapper.searchCmsContentComments(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }

    @Override
    public CmsContentCommentDto wrapDto(CmsContentCommentPo po) {
        if (po == null) { return null; }
        CmsContentCommentDto dto = new CmsContentCommentDto();
        dto.setId(po.getId());
        dto.setTitle(po.getTitle());
        dto.setContent(po.getContent());
        dto.setImageUrl(po.getImageUrl());
        dto.setSiteId(po.getSiteId());
        dto.setContentId(po.getContentId());
        dto.setCommontUserId(po.getCommontUserId());
        dto.setStatus(po.getStatus());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}