package com.feihua.framework.cms.impl;

import com.feihua.framework.cms.api.ApiCmsQuestionPoService;
import com.feihua.framework.cms.dto.CmsQuestionDto;
import com.feihua.framework.cms.po.CmsQuestionPo;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-01-17 14:00:41
 */
@Service
public class ApiCmsQuestionPoServiceImpl extends ApiBaseServiceImpl<CmsQuestionPo, CmsQuestionDto, String> implements ApiCmsQuestionPoService {
    @Autowired
    com.feihua.framework.cms.mapper.CmsQuestionPoMapper CmsQuestionPoMapper;

    public ApiCmsQuestionPoServiceImpl() {
        super(CmsQuestionDto.class);
    }

    @Override
    public PageResultDto<CmsQuestionDto> searchCmsQuestionsDsf(com.feihua.framework.cms.dto.SearchCmsQuestionsConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.feihua.framework.cms.dto.CmsQuestionDto> list = this.wrapDtos(CmsQuestionPoMapper.searchCmsQuestions(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }

    @Override
    public CmsQuestionDto wrapDto(CmsQuestionPo po) {
        if (po == null) { return null; }
        CmsQuestionDto dto = new CmsQuestionDto();
        dto.setId(po.getId());
        dto.setSurveyId(po.getSurveyId());
        dto.setName(po.getName());
        dto.setType(po.getType());
        dto.setBr(po.getBr());
        dto.setSequence(po.getSequence());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}