package com.feihua.framework.statistic.impl;

import com.feihua.framework.statistic.api.ApiStatisticRecordPageViewPoService;
import com.feihua.framework.statistic.dto.StatisticRecordPageViewDto;
import com.feihua.framework.statistic.po.StatisticRecordPageViewPo;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-28 18:02:47
 */
@Service
public class ApiStatisticRecordPageViewPoServiceImpl extends ApiBaseServiceImpl<StatisticRecordPageViewPo, StatisticRecordPageViewDto, String> implements ApiStatisticRecordPageViewPoService {
    @Autowired
    com.feihua.framework.statistic.mapper.StatisticRecordPageViewPoMapper StatisticRecordPageViewPoMapper;

    public ApiStatisticRecordPageViewPoServiceImpl() {
        super(StatisticRecordPageViewDto.class);
    }

    @Override
    public PageResultDto<StatisticRecordPageViewDto> searchStatisticRecordPageViewsDsf(com.feihua.framework.statistic.dto.SearchStatisticRecordPageViewsConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.feihua.framework.statistic.dto.StatisticRecordPageViewDto> list = this.wrapDtos(StatisticRecordPageViewPoMapper.searchStatisticRecordPageViews(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }

    @Override
    public StatisticRecordPageViewDto wrapDto(StatisticRecordPageViewPo po) {
        if (po == null) { return null; }
        StatisticRecordPageViewDto dto = new StatisticRecordPageViewDto();
        dto.setId(po.getId());
        dto.setUrl(po.getUrl());
        dto.setUserId(po.getUserId());
        dto.setUserNickname(po.getUserNickname());
        dto.setType(po.getType());
        dto.setContentId(po.getContentId());
        dto.setContentName(po.getContentName());
        dto.setWhereFrom(po.getWhereFrom());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        dto.setFromUserId(po.getFromUserId());
        dto.setFromUserNickname(po.getFromUserNickname());
        return dto;
    }
}