package com.feihua.framework.statistic.impl;

import com.feihua.framework.statistic.api.ApiStatisticUserAreaCountPoService;
import com.feihua.framework.statistic.dto.StatisticUserAreaCountDto;
import com.feihua.framework.statistic.po.StatisticUserAreaCountPo;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-25 11:13:39
 */
@Service
public class ApiStatisticUserAreaCountPoServiceImpl extends ApiBaseServiceImpl<StatisticUserAreaCountPo, StatisticUserAreaCountDto, String> implements ApiStatisticUserAreaCountPoService {
    @Autowired
    com.feihua.framework.statistic.mapper.StatisticUserAreaCountPoMapper StatisticUserAreaCountPoMapper;

    public ApiStatisticUserAreaCountPoServiceImpl() {
        super(StatisticUserAreaCountDto.class);
    }

    @Override
    public StatisticUserAreaCountDto wrapDto(StatisticUserAreaCountPo po) {
        if (po == null) { return null; }
        StatisticUserAreaCountDto dto = new StatisticUserAreaCountDto();
        dto.setId(po.getId());
        dto.setAreaId(po.getAreaId());
        dto.setAreaName(po.getAreaName());
        dto.setBatchNo(po.getBatchNo());
        dto.setAllNum(po.getAllNum());
        dto.setMaleNum(po.getMaleNum());
        dto.setFemaleNum(po.getFemaleNum());
        dto.setGenderOtherNum(po.getGenderOtherNum());
        dto.setOnlineAllNum(po.getOnlineAllNum());
        dto.setOnlineMaleNum(po.getOnlineMaleNum());
        dto.setOnlineFemaleNum(po.getOnlineFemaleNum());
        dto.setOnlineGenderOtherNum(po.getOnlineGenderOtherNum());
        dto.setLongitude(po.getLongitude());
        dto.setLatitude(po.getLatitude());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}