package com.feihua.framework.statistic.impl;

import com.feihua.framework.statistic.api.ApiStatisticUserCountPoService;
import com.feihua.framework.statistic.dto.StatisticUserCountDto;
import com.feihua.framework.statistic.po.StatisticUserCountPo;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-23 09:19:52
 */
@Service
public class ApiStatisticUserCountPoServiceImpl extends ApiBaseServiceImpl<StatisticUserCountPo, StatisticUserCountDto, String> implements ApiStatisticUserCountPoService {
    @Autowired
    com.feihua.framework.statistic.mapper.StatisticUserCountPoMapper StatisticUserCountPoMapper;

    public ApiStatisticUserCountPoServiceImpl() {
        super(StatisticUserCountDto.class);
    }

    @Override
    public StatisticUserCountDto wrapDto(StatisticUserCountPo po) {
        if (po == null) { return null; }
        StatisticUserCountDto dto = new StatisticUserCountDto();
        dto.setId(po.getId());
        dto.setBatchNo(po.getBatchNo());
        dto.setAllNum(po.getAllNum());
        dto.setMaleNum(po.getMaleNum());
        dto.setFemaleNum(po.getFemaleNum());
        dto.setGenderOtherNum(po.getGenderOtherNum());
        dto.setOnlineAllNum(po.getOnlineAllNum());
        dto.setOnlineMaleNum(po.getOnlineMaleNum());
        dto.setOnlineFemaleNum(po.getOnlineFemaleNum());
        dto.setOnlineGenderOtherNum(po.getOnlineGenderOtherNum());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}