package com.feihua.framework.statistic.impl;

import com.feihua.framework.statistic.api.ApiStatisticRecordPageSharePoService;
import com.feihua.framework.statistic.dto.StatisticRecordPageShareDto;
import com.feihua.framework.statistic.po.StatisticRecordPageSharePo;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-28 14:00:30
 */
@Service
public class ApiStatisticRecordPageSharePoServiceImpl extends ApiBaseServiceImpl<StatisticRecordPageSharePo, StatisticRecordPageShareDto, String> implements ApiStatisticRecordPageSharePoService {
    @Autowired
    com.feihua.framework.statistic.mapper.StatisticRecordPageSharePoMapper StatisticRecordPageSharePoMapper;

    public ApiStatisticRecordPageSharePoServiceImpl() {
        super(StatisticRecordPageShareDto.class);
    }

    @Override
    public PageResultDto<StatisticRecordPageShareDto> searchStatisticRecordPageSharesDsf(com.feihua.framework.statistic.dto.SearchStatisticRecordPageSharesConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.feihua.framework.statistic.dto.StatisticRecordPageShareDto> list = this.wrapDtos(StatisticRecordPageSharePoMapper.searchStatisticRecordPageShares(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }

    @Override
    public StatisticRecordPageShareDto wrapDto(StatisticRecordPageSharePo po) {
        if (po == null) { return null; }
        StatisticRecordPageShareDto dto = new StatisticRecordPageShareDto();
        dto.setId(po.getId());
        dto.setUrl(po.getUrl());
        dto.setUserId(po.getUserId());
        dto.setUserNickname(po.getUserNickname());
        dto.setType(po.getType());
        dto.setContentId(po.getContentId());
        dto.setContentName(po.getContentName());
        dto.setShareTo(po.getShareTo());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}