package com.feihua.framework.spider.api;

import com.feihua.framework.spider.dto.SpiderConfigSourceDto;
import com.feihua.framework.spider.po.SpiderConfigSourcePo;
import feihua.jdbc.api.pojo.PageResultDto;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-19 17:13:35
 */
public interface ApiSpiderConfigSourcePoService extends feihua.jdbc.api.service.ApiBaseService<SpiderConfigSourcePo, SpiderConfigSourceDto, String> {
    PageResultDto<SpiderConfigSourceDto> searchSpiderConfigSourcesDsf(com.feihua.framework.spider.dto.SearchSpiderConfigSourcesConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto);

    SpiderConfigSourcePo selectByDomain(String domain);
}