package com.feihua.framework.rest.modules.loginclient.dto;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_login_client
 *
 * @mbg.generated 2019-04-04 11:42:32
*/
public class AddBaseLoginClientFormDto {

    private String clientCode;

    private String clientName;

    private String clientType;
    private String clientMaxnum;

    private String description;

    public String getClientCode() {
        return clientCode;
    }

    public void setClientCode(String clientCode) {
        this.clientCode = clientCode;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientType() {
        return clientType;
    }

    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getClientMaxnum() {
        return clientMaxnum;
    }

    public void setClientMaxnum(String clientMaxnum) {
        this.clientMaxnum = clientMaxnum;
    }
}