package com.feihua.framework.base.modules.office.dto;

import feihua.jdbc.api.pojo.BaseDto;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_office
 *
 * @mbg.generated 2018-01-05 15:51:59
*/
public class BaseOfficeDto extends BaseDto {
    private String id;

    private String name;

    private String areaId;

    private String type;

    private Integer level;

    private String address;

    private String zipCode;

    private String master;

    private String phone;

    private String fax;

    private String email;

    private String primaryUserId;

    private String deputyUserId;

    private String parentId;

    private String parentId1;

    private String parentId2;

    private String parentId3;

    private String parentId4;

    private String parentId5;

    private String parentId6;

    private String parentId7;

    private String parentId8;

    private String parentId9;

    private String parentId10;

    private String dataUserId;

    private String dataOfficeId;

    private String dataType;

    private String dataAreaId;

    private String delFlag;

    private Date createAt;

    private String createBy;

    private Date updateAt;

    private String updateBy;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getMaster() {
        return master;
    }

    public void setMaster(String master) {
        this.master = master;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPrimaryUserId() {
        return primaryUserId;
    }

    public void setPrimaryUserId(String primaryUserId) {
        this.primaryUserId = primaryUserId;
    }

    public String getDeputyUserId() {
        return deputyUserId;
    }

    public void setDeputyUserId(String deputyUserId) {
        this.deputyUserId = deputyUserId;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getParentId1() {
        return parentId1;
    }

    public void setParentId1(String parentId1) {
        this.parentId1 = parentId1;
    }

    public String getParentId2() {
        return parentId2;
    }

    public void setParentId2(String parentId2) {
        this.parentId2 = parentId2;
    }

    public String getParentId3() {
        return parentId3;
    }

    public void setParentId3(String parentId3) {
        this.parentId3 = parentId3;
    }

    public String getParentId4() {
        return parentId4;
    }

    public void setParentId4(String parentId4) {
        this.parentId4 = parentId4;
    }

    public String getParentId5() {
        return parentId5;
    }

    public void setParentId5(String parentId5) {
        this.parentId5 = parentId5;
    }

    public String getParentId6() {
        return parentId6;
    }

    public void setParentId6(String parentId6) {
        this.parentId6 = parentId6;
    }

    public String getParentId7() {
        return parentId7;
    }

    public void setParentId7(String parentId7) {
        this.parentId7 = parentId7;
    }

    public String getParentId8() {
        return parentId8;
    }

    public void setParentId8(String parentId8) {
        this.parentId8 = parentId8;
    }

    public String getParentId9() {
        return parentId9;
    }

    public void setParentId9(String parentId9) {
        this.parentId9 = parentId9;
    }

    public String getParentId10() {
        return parentId10;
    }

    public void setParentId10(String parentId10) {
        this.parentId10 = parentId10;
    }

    public String getDataUserId() {
        return dataUserId;
    }

    public void setDataUserId(String dataUserId) {
        this.dataUserId = dataUserId;
    }

    public String getDataOfficeId() {
        return dataOfficeId;
    }

    public void setDataOfficeId(String dataOfficeId) {
        this.dataOfficeId = dataOfficeId;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getDataAreaId() {
        return dataAreaId;
    }

    public void setDataAreaId(String dataAreaId) {
        this.dataAreaId = dataAreaId;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public Date getCreateAt() {
        return createAt;
    }

    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Date getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
}