package com.wwd.service.mapper;

import com.wwd.service.modules.wwd.po.WwdUserTagPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-04-25 11:25:16
 */
public interface WwdUserTagPoMapper extends feihua.jdbc.api.dao.CrudDao<WwdUserTagPo, String> {
}