package com.wwd.service.mapper;

import com.wwd.service.modules.wwd.po.WwdUserInvitationPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-04-27 09:40:48
 */
public interface WwdUserInvitationPoMapper extends feihua.jdbc.api.dao.CrudDao<WwdUserInvitationPo, String> {
}