package com.feihua.framework.base.modules.office.api;

import com.feihua.framework.base.modules.office.dto.BaseOfficeDataScopeDefineSelfDto;
import com.feihua.framework.base.modules.office.po.BaseOfficeDataScopeDefineSelfPo;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-03-19 18:39:44
 */
public interface ApiBaseOfficeDataScopeDefineSelfPoService extends feihua.jdbc.api.service.ApiBaseService<BaseOfficeDataScopeDefineSelfPo, BaseOfficeDataScopeDefineSelfDto, String> {


    /**
     * 插入机构数据范围定义与机构自定义的关系
     * @param officeIds
     * @param officeDataScopeDefineId
     * @param currentUserId 当前登录用户
     * @return
     */
    public int insertOfficeSelf(List<String> officeIds, String officeDataScopeDefineId, String currentUserId);

    /**
     * 根据机构数据范围定义id删除自定义关系
     * @param officeDataScopeDefineId
     * @param currentUserId
     * @return
     */
    public int deleteOfficeSelfByOfficeDataScopeDefineId(String officeDataScopeDefineId, String currentUserId);

    /**
     * 根据机构数据范围定义id查询自定义设置的机构ids
     * @param officeDataScopeDefineId
     * @return
     */
    public List<BaseOfficeDataScopeDefineSelfDto> selectByOfficeDataScopeDefineId(String officeDataScopeDefineId);
}