package com.feihua.framework.cms.api;

import com.feihua.framework.cms.dto.CmsChannelPageViewDto;
import com.feihua.framework.cms.po.CmsChannelPageViewPo;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-11-09 16:53:22
 */
public interface ApiCmsChannelPageViewPoService extends feihua.jdbc.api.service.ApiBaseService<CmsChannelPageViewPo, CmsChannelPageViewDto, String> {

    /**
     * 计算iv
     * 计算date参数所在的日期当天的iv数量
     * @param channelId
     * @param date
     * @return
     */
    public int computeIv(String channelId, Date date);

    /**
     * 计算date参数所在的日期当天的host的记录数量
     * @param host
     * @param date
     * @return
     */
    public int existHost(String host, Date date);

    /**
     * 计算uv
     * 计算date参数所在的日期当天的uv数量
     * @param channelId
     * @param date
     * @return
     */
    public int computeUv(String channelId, Date date);

    /**
     * 计算date参数所在的日期当天的cookie的记录数量
     * @param cookie
     * @param date
     * @return
     */
    public int existCookie(String cookie, Date date);
}