package com.feihua.framework.cms.api;

import com.feihua.framework.cms.dto.CmsContentVideoDto;
import com.feihua.framework.cms.po.CmsContentVideoPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-13 14:46:05
 */
public interface ApiCmsContentVideoPoService extends feihua.jdbc.api.service.ApiBaseService<CmsContentVideoPo, CmsContentVideoDto, String> {

    CmsContentVideoPo selectBySiteIdAndContentId(String siteId,String contentId);

}