package com.feihua.framework.cms.api;

import com.feihua.framework.cms.dto.CmsSiteDto;
import com.feihua.framework.cms.po.CmsSitePo;
import feihua.jdbc.api.pojo.PageResultDto;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-11-09 16:15:06
 */
public interface ApiCmsSitePoService extends feihua.jdbc.api.service.ApiBaseService<CmsSitePo, CmsSiteDto, String> {
    PageResultDto<CmsSiteDto> searchCmsSitesDsf(com.feihua.framework.cms.dto.SearchCmsSitesConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto);

    /**
     * 根据域名查询主站
     * @param domain
     * @return
     */
    CmsSitePo selecltMainSiteByDomain(String domain);
    List<CmsSitePo> selecltByDomain(String domain);
    CmsSitePo selecltByPath(String siteContextPath);
}