package com.feihua.framework.cms.api;

import com.feihua.framework.cms.dto.CmsChannelPageViewDto;
import com.feihua.framework.cms.po.CmsChannelPageViewPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-11-09 16:53:22
 */
public interface ApiCmsChannelPageViewPoService extends feihua.jdbc.api.service.ApiBaseService<CmsChannelPageViewPo, CmsChannelPageViewDto, String> {
}