package com.feihua.framework.cms.api;

import com.feihua.framework.cms.dto.CmsContentAudioDto;
import com.feihua.framework.cms.po.CmsContentAudioPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-13 14:45:35
 */
public interface ApiCmsContentAudioPoService extends feihua.jdbc.api.service.ApiBaseService<CmsContentAudioPo, CmsContentAudioDto, String> {

    CmsContentAudioPo selectBySiteIdAndContentId(String siteId,String contentId);

}