package com.feihua.framework.cms.api;

import com.feihua.framework.cms.dto.CmsContentLibraryDto;
import com.feihua.framework.cms.po.CmsContentLibraryPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-06 15:42:29
 */
public interface ApiCmsContentLibraryPoService extends feihua.jdbc.api.service.ApiBaseService<CmsContentLibraryPo, CmsContentLibraryDto, String> {

    CmsContentLibraryPo selectBySiteIdAndContentId(String siteId,String contentId);
}