package com.feihua.framework.cms.api;

import com.feihua.framework.cms.dto.CmsContentCategoryRelDto;
import com.feihua.framework.cms.po.CmsContentCategoryRelPo;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-06 15:38:46
 */
public interface ApiCmsContentCategoryRelPoService extends feihua.jdbc.api.service.ApiBaseService<CmsContentCategoryRelPo, CmsContentCategoryRelDto, String> {


    /**
     * 根据站点id和内容id查询
     * @param siteId 必填
     * @param contentId 选填 不填只根据站点id查询
     * @return
     */
    List<CmsContentCategoryRelPo> selectBySiteIdAndContentId(String siteId,String contentId);

    /**
     * 根据站点id和分类id查询
     * @param siteId 必填
     * @param categoryId 选填 不填只根据站点id查询
     * @return
     */
    List<CmsContentCategoryRelPo> selectBySiteIdAndCategoryId(String siteId,String categoryId);

    /**
     * 删除
     * @param siteId 必填
     * @param contentId 必填
     * @return
     */
    int deleteBySiteIdAndContentId(String siteId,String contentId,String currentUserId);
}