package com.feihua.framework.message.dto;

import feihua.jdbc.api.pojo.BaseConditionDto;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_message_template
 *
 * @mbg.generated 2018-10-29 20:18:23
*/
public class SearchBaseMessageTemplatesConditionDto extends BaseConditionDto {

    private String name;

    private String code;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}