package com.feihua.framework.base.modules.message.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-31 12:43:49
 *
 * This class corresponds to the database table base_message_target_client
 * @mbg.generated do_not_delete_during_merge 2018-10-31 12:43:49
*/
public class BaseMessageTargetClientPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   消息id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_message_target_client.MESSAGE_ID
     *
     * @mbg.generated 2018-10-31 12:43:49
     */
    private String messageId;

    /**
     * Database Column Remarks:
     *   消息目标客户端，如：pc,miniprogram等，如果客户端还有分类请自行处理（如支持多个小程序，公众号的场景）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_message_target_client.TARGET_CLIENT
     *
     * @mbg.generated 2018-10-31 12:43:49
     */
    private String targetClient;

    /**
     * Database Column Remarks:
     *   消息目标客户端子分类（如支持多个小程序，公众号的场景）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_message_target_client.SUB_TARGET_CLIENT
     *
     * @mbg.generated 2018-10-31 12:43:49
     */
    private String subTargetClient;

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getTargetClient() {
        return targetClient;
    }

    public void setTargetClient(String targetClient) {
        this.targetClient = targetClient;
    }

    public String getSubTargetClient() {
        return subTargetClient;
    }

    public void setSubTargetClient(String subTargetClient) {
        this.subTargetClient = subTargetClient;
    }

    public com.feihua.framework.base.modules.message.api.ApiBaseMessageTargetClientPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.base.modules.message.api.ApiBaseMessageTargetClientPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", messageId=").append(messageId);
        sb.append(", targetClient=").append(targetClient);
        sb.append(", subTargetClient=").append(subTargetClient);
        sb.append("]");
        return sb.toString();
    }
}