package com.feihua.framework.base.modules.rel.api;

import com.feihua.framework.base.modules.rel.dto.BaseUserGroupDataScopeRelDto;
import com.feihua.framework.base.modules.rel.po.BaseUserGroupDataScopeRelPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-20 13:28:16
 */
public interface ApiBaseUserGroupDataScopeRelPoService extends feihua.jdbc.api.service.ApiBaseService<BaseUserGroupDataScopeRelPo, BaseUserGroupDataScopeRelDto, String> {
}