package com.feihua.framework.base.modules.rel.api;

import com.feihua.framework.base.modules.user.dto.BaseUserRolePostSwitchDto;
import com.feihua.framework.base.modules.user.po.BaseUserRolePostSwitchPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-13 19:36:06
 */
public interface ApiBaseUserRolePostSwitchPoService extends feihua.jdbc.api.service.ApiBaseService<BaseUserRolePostSwitchPo, BaseUserRolePostSwitchDto, String> {

    /**
     * 根据用户查询
     * @param userId
     * @return
     */
    BaseUserRolePostSwitchPo selectByUserId(String userId);
}