package com.feihua.framework.log.service.api;

import com.feihua.framework.log.service.dto.BaseLogDto;
import com.feihua.framework.log.service.po.BaseLogPo;
import com.feihua.framework.log.service.dto.SearchBaseLogsConditionDto;
import feihua.jdbc.api.pojo.PageResultDto;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-01-10 13:43:14
 */
public interface ApiBaseLogPoService extends feihua.jdbc.api.service.ApiBaseService<BaseLogPo, BaseLogDto, String> {
    PageResultDto<BaseLogDto> searchBaseLogsDsf(SearchBaseLogsConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto);
}