package com.feihua.framework.message.mapper;

import com.feihua.framework.message.po.BaseMessageTemplateThirdBindPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-29 15:38:33
 */
public interface BaseMessageTemplateThirdBindPoMapper extends feihua.jdbc.api.dao.CrudDao<BaseMessageTemplateThirdBindPo, String> {
}