package com.feihua.framework.message.mapper;

import com.feihua.framework.message.po.BaseMessageSendPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-29 16:01:58
 */
public interface BaseMessageSendPoMapper extends feihua.jdbc.api.dao.CrudDao<BaseMessageSendPo, String> {
    int updateByPrimaryKeyWithBLOBs(BaseMessageSendPo record);
}