package com.feihua.framework.message.mapper;

import com.feihua.framework.message.dto.SearchBaseMessageTemplatesConditionDto;
import com.feihua.framework.message.po.BaseMessageTemplatePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-29 20:18:23
 */
public interface BaseMessageTemplatePoMapper extends feihua.jdbc.api.dao.CrudDao<BaseMessageTemplatePo, String> {
    java.util.List<BaseMessageTemplatePo> searchBaseMessageTemplates(SearchBaseMessageTemplatesConditionDto dto);
}