package com.feihua.framework.message.mapper;

import com.feihua.framework.message.dto.SearchBaseMessagesConditionDto;
import com.feihua.framework.message.dto.SearchUserMessageConditionDto;
import com.feihua.framework.message.dto.UserMessageDto;
import com.feihua.framework.message.po.BaseMessagePo;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-29 19:58:54
 */
public interface BaseMessagePoMapper extends feihua.jdbc.api.dao.CrudDao<BaseMessagePo, String> {

    List<BaseMessagePo> searchBaseMessages(SearchBaseMessagesConditionDto dto);

    List<UserMessageDto> searchUserMessage(SearchUserMessageConditionDto dto);
}