package com.feihua.framework.message.mapper;

import com.feihua.framework.message.po.BaseMessageSendPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-07 14:28:52
 */
public interface BaseMessageSendPoMapper extends feihua.jdbc.api.dao.CrudDao<BaseMessageSendPo, String> {
}