package com.feihua.framework.message.mapper;

import com.feihua.framework.message.po.BaseMessageVUserPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-07 15:21:48
 */
public interface BaseMessageVUserPoMapper extends feihua.jdbc.api.dao.CrudDao<BaseMessageVUserPo, String> {
}