package com.feihua.framework.statistic.api;

import com.feihua.framework.statistic.dto.StatisticUserAreaCountDto;
import com.feihua.framework.statistic.po.StatisticUserAreaCountPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-23 09:21:58
 */
public interface ApiStatisticUserAreaCountPoService extends feihua.jdbc.api.service.ApiBaseService<StatisticUserAreaCountPo, StatisticUserAreaCountDto, String> {
}