package com.feihua.framework.statistic.api;

import com.feihua.framework.statistic.dto.StatisticUserClientCountHistoryDto;
import com.feihua.framework.statistic.po.StatisticUserClientCountHistoryPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-23 09:21:26
 */
public interface ApiStatisticUserClientCountHistoryPoService extends feihua.jdbc.api.service.ApiBaseService<StatisticUserClientCountHistoryPo, StatisticUserClientCountHistoryDto, String> {
}