package com.feihua.framework.cms.dto;

import com.feihua.framework.cms.CmsConstants;
import com.feihua.utils.http.httpServletRequest.RequestUtils;
import com.feihua.utils.io.FileUtils;
import feihua.jdbc.api.pojo.BaseDto;
import org.apache.commons.lang3.StringUtils;

import java.util.Date;

import static com.feihua.framework.cms.CmsConstants.suffixHtm;
import static com.feihua.framework.cms.CmsConstants.suffixHtml;
import static com.feihua.framework.cms.CmsConstants.templatePathDefault;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_site
 *
 * @mbg.generated 2018-11-19 13:31:12
*/
public class CmsSiteTemplateModelDto extends BaseDto {

    public CmsSiteTemplateModelDto(CmsSiteDto siteDto,CmsTemplateModelContextDto contextDto) {
        this.id = siteDto.getId();
        this.name = siteDto.getName();
        this.domain = siteDto.getDomain();
        this.path = siteDto.getPath();
        this.templatePath = siteDto.getTemplatePath();
        this.template = siteDto.getTemplate();
        this.staticPath = siteDto.getStaticPath();
        this.isMain = siteDto.getIsMain();
        this.dataUserId = siteDto.getDataUserId();
        this.dataOfficeId = siteDto.getDataOfficeId();
        this.dataType = siteDto.getDataType();
        this.dataAreaId = siteDto.getDataAreaId();
        this.delFlag = siteDto.getDelFlag();
        this.createAt = siteDto.getCreateAt();
        this.createBy = siteDto.getCreateBy();
        this.updateAt = siteDto.getUpdateAt();
        this.updateBy = siteDto.getUpdateBy();
        this.deployPath = siteDto.getDeployPath();
        this.pv = siteDto.getPv();
        this.iv = siteDto.getIv();
        this.uv = siteDto.getUv();
        this.contextDto = contextDto;
    }

    private String id;

    private String name;

    private String domain;

    private String path;

    private String templatePath;

    private String template;

    private String staticPath;

    private String isMain;

    private String dataUserId;

    private String dataOfficeId;

    private String dataType;

    private String dataAreaId;

    private String delFlag;

    private Date createAt;

    private String createBy;

    private Date updateAt;
    private Integer pv;

    private Integer iv;

    private Integer uv;
    private String updateBy;
    private String deployPath;

    private CmsTemplateModelContextDto contextDto;

    //addtional

    public String getSitePath() {


        if (contextDto.isDynamic()) {

            return getDomain() + getDeployPath() + CmsConstants.requestPathPrefix + getPath();
        }else{
            String _staticPath = getStaticPath();
            if(StringUtils.isEmpty(_staticPath)){
                _staticPath = this.id;
            }
            return getDomain() + RequestUtils.wrapStartSlash(_staticPath);
        }

    }
    public String getSuffix() {
        return contextDto.isDynamic() ? suffixHtm : suffixHtml;
    }
    public String getIndexUrl() {
        return getSitePath() + FileUtils.slash + CmsConstants.index +  getSuffix() ;
    }

    /**
     * 该方法仅适用于默认的规则，即：静态资源存放于 /static/template-cms/ + 模板路径 目录下
     * @return
     */
    public String getStaticResourcePath() {

        String _staticPath = getTemplatePath();
        if(StringUtils.isEmpty(_staticPath)){
            _staticPath = templatePathDefault;
        }
        return getDeployPath() + CmsConstants.staticPath +  CmsConstants.templateRootPath + _staticPath;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDomain() {
        if( !StringUtils.isEmpty(this.domain)){
            return RequestUtils.unwrapEndSlash(this.domain);
        }
        return "";
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getPath() {
        if( !StringUtils.isEmpty(this.path)){
            return RequestUtils.wrapStartSlash(this.path);
        }
        return "";
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getTemplatePath() {
        if( !StringUtils.isEmpty(this.templatePath)){
            return RequestUtils.wrapStartSlash(this.templatePath);
        }
        return "";
    }

    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath;
    }

    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public String getStaticPath() {
        if( !StringUtils.isEmpty(this.staticPath)){
            return RequestUtils.wrapStartSlash(this.staticPath);
        }
        return "";
    }

    public void setStaticPath(String staticPath) {
        this.staticPath = staticPath;
    }

    public String getIsMain() {
        return isMain;
    }

    public void setIsMain(String isMain) {
        this.isMain = isMain;
    }

    public String getDataUserId() {
        return dataUserId;
    }

    public void setDataUserId(String dataUserId) {
        this.dataUserId = dataUserId;
    }

    public String getDataOfficeId() {
        return dataOfficeId;
    }

    public void setDataOfficeId(String dataOfficeId) {
        this.dataOfficeId = dataOfficeId;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getDataAreaId() {
        return dataAreaId;
    }

    public void setDataAreaId(String dataAreaId) {
        this.dataAreaId = dataAreaId;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public Date getCreateAt() {
        return createAt;
    }

    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Date getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public String getDeployPath() {
        if( !StringUtils.isEmpty(this.deployPath)){
            return RequestUtils.wrapStartSlash(this.deployPath);
        }

        return "";
    }

    public void setDeployPath(String deployPath) {
        this.deployPath = deployPath;
    }

    public CmsTemplateModelContextDto getContextDto() {
        return contextDto;
    }

    public void setContextDto(CmsTemplateModelContextDto contextDto) {
        this.contextDto = contextDto;
    }

    public Integer getPv() {
        return pv;
    }

    public void setPv(Integer pv) {
        this.pv = pv;
    }

    public Integer getIv() {
        return iv;
    }

    public void setIv(Integer iv) {
        this.iv = iv;
    }

    public Integer getUv() {
        return uv;
    }

    public void setUv(Integer uv) {
        this.uv = uv;
    }
}