package com.feihua.framework.message.impl;

import com.feihua.framework.message.api.ApiBaseMessageClientPoService;
import com.feihua.framework.message.dto.BaseMessageClientDto;
import com.feihua.framework.message.po.BaseMessageClientPo;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-25 17:26:10
 */
@Service
public class ApiBaseMessageClientPoServiceImpl extends ApiBaseServiceImpl<BaseMessageClientPo, BaseMessageClientDto, String> implements ApiBaseMessageClientPoService {
    @Autowired
    com.feihua.framework.message.mapper.BaseMessageClientPoMapper BaseMessageClientPoMapper;

    public ApiBaseMessageClientPoServiceImpl() {
        super(BaseMessageClientDto.class);
    }

    @Override
    public BaseMessageClientDto wrapDto(BaseMessageClientPo po) {
        if (po == null) { return null; }
        BaseMessageClientDto dto = new BaseMessageClientDto();
        dto.setId(po.getId());
        dto.setMessageId(po.getMessageId());
        dto.setClientId(po.getClientId());
        dto.setMessageState(po.getMessageState());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}