package com.feihua.framework.spider.po;

import com.feihua.framework.spider.api.ApiSpiderResultPoService;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-19 17:20:07
 * Database Table Remarks:
 *   爬虫文档结果
 *
 * This class corresponds to the database table spider_result
 * @mbg.generated do_not_delete_during_merge 2018-12-19 17:20:07
*/
public class SpiderResultPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   配置源id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_result.CONFIG_SOURCE_ID
     *
     * @mbg.generated 2018-12-19 17:20:07
     */
    private String configSourceId;

    /**
     * Database Column Remarks:
     *   内容地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_result.URL
     *
     * @mbg.generated 2018-12-19 17:20:07
     */
    private String url;

    /**
     * Database Column Remarks:
     *   内容类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_result.CONTENT_TYPE
     *
     * @mbg.generated 2018-12-19 17:20:07
     */
    private String contentType;

    /**
     * Database Column Remarks:
     *   文档网页标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_result.TITLE
     *
     * @mbg.generated 2018-12-19 17:20:07
     */
    private String title;

    /**
     * Database Column Remarks:
     *   上一个结果的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_result.PARENT_ID
     *
     * @mbg.generated 2018-12-19 17:20:07
     */
    private String parentId;

    /**
     * Database Column Remarks:
     *   内容doc
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_result.DOCUMENT
     *
     * @mbg.generated 2018-12-19 17:20:07
     */
    private String document;

    public String getConfigSourceId() {
        return configSourceId;
    }

    public void setConfigSourceId(String configSourceId) {
        this.configSourceId = configSourceId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getDocument() {
        return document;
    }

    public void setDocument(String document) {
        this.document = document;
    }

    public ApiSpiderResultPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(ApiSpiderResultPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", configSourceId=").append(configSourceId);
        sb.append(", url=").append(url);
        sb.append(", contentType=").append(contentType);
        sb.append(", title=").append(title);
        sb.append(", parentId=").append(parentId);
        sb.append(", document=").append(document);
        sb.append("]");
        return sb.toString();
    }
}