package com.feihua.framework.cms.mapper;

import com.feihua.framework.cms.po.CmsContentAttachmentPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-06 15:40:14
 */
public interface CmsContentAttachmentPoMapper extends feihua.jdbc.api.dao.CrudDao<CmsContentAttachmentPo, String> {
}