package com.feihua.framework.cms.mapper;

import com.feihua.framework.cms.po.CmsContentCategoryRelPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-06 15:38:46
 */
public interface CmsContentCategoryRelPoMapper extends feihua.jdbc.api.dao.CrudDao<CmsContentCategoryRelPo, String> {
}