package com.feihua.framework.cms.mapper;

import com.feihua.framework.cms.po.CmsContentDownloadImagePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-26 09:44:06
 */
public interface CmsContentDownloadImagePoMapper extends feihua.jdbc.api.dao.CrudDao<CmsContentDownloadImagePo, String> {
}