package com.feihua.framework.cms.mapper;

import com.feihua.framework.cms.po.CmsContentPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-11-09 16:57:39
 */
public interface CmsContentPoMapper extends feihua.jdbc.api.dao.CrudDao<CmsContentPo, String> {

    java.util.List<CmsContentPo> searchCmsContents(com.feihua.framework.cms.dto.SearchCmsContentsConditionDto dto);
}