package com.feihua.framework.cms.mapper;

import com.feihua.framework.cms.po.CmsContentVedioOtherPlayerPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-24 13:42:45
 */
public interface CmsContentVedioOtherPlayerPoMapper extends feihua.jdbc.api.dao.CrudDao<CmsContentVedioOtherPlayerPo, String> {
}