package com.feihua.framework.cms.mapper;

import com.feihua.framework.cms.po.CmsContentLibraryImagePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-06 15:43:19
 */
public interface CmsContentLibraryImagePoMapper extends feihua.jdbc.api.dao.CrudDao<CmsContentLibraryImagePo, String> {
}