package com.feihua.framework.cms.mapper;

import com.feihua.framework.cms.po.CmsQuestionOptionsPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-01-17 14:03:09
 */
public interface CmsQuestionOptionsPoMapper extends feihua.jdbc.api.dao.CrudDao<CmsQuestionOptionsPo, String> {
    java.util.List<CmsQuestionOptionsPo> searchCmsQuestionOptionss(com.feihua.framework.cms.dto.SearchCmsQuestionOptionssConditionDto dto);
}