package com.wwd.service.modules.wwd.dto;

import feihua.jdbc.api.pojo.BaseConditionDto;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wwd_user_card
 *
 * @mbg.generated 2018-11-01 10:44:36
*/
public class SearchWwdUserCardsConditionDto extends BaseConditionDto {

    private String wwdUserId;

    private String type;

    public String getWwdUserId() {
        return wwdUserId;
    }

    public void setWwdUserId(String wwdUserId) {
        this.wwdUserId = wwdUserId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}