package com.feihua.wechat.common.po;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-07-20 18:10:04
 *
 * This class corresponds to the database table weixin_user
 * @mbg.generated do_not_delete_during_merge 2018-07-20 18:10:04
*/
public class WeixinUserPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.USER_ID
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   类型，标识是小程序还是公众号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.TYPE
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String type;

    /**
     * Database Column Remarks:
     *   字典，标识哪一个公众号，或小程序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.WHICH
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String which;

    /**
     * Database Column Remarks:
     *   微信openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.OPENID
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String openid;

    /**
     * Database Column Remarks:
     *   微信全局id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.UNIONID
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String unionid;

    /**
     * Database Column Remarks:
     *   微信昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.NICKNAME
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.CITY
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String city;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.PROVINCE
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String province;

    /**
     * Database Column Remarks:
     *   国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.COUNTRY
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String country;

    /**
     * Database Column Remarks:
     *   头像地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.HEAD_IMAGE_URL
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String headImageUrl;

    /**
     * Database Column Remarks:
     *   语言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.LANGUAGE
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String language;

    /**
     * Database Column Remarks:
     *   经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.LONGITUDE
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String longitude;

    /**
     * Database Column Remarks:
     *   纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.LATITUDE
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String latitude;

    /**
     * Database Column Remarks:
     *   地理位置精度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.PRECISIONS
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String precisions;

    /**
     * Database Column Remarks:
     *   性别，微信的性别标识，1=男，2=女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.GENDER
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   地理位置描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.LOCATION
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String location;

    /**
     * Database Column Remarks:
     *   用户来源，标识用户是怎么来的，如关注公众号、直接获取用户信息等
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.HOW_FROM
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String howFrom;

    /**
     * Database Column Remarks:
     *   状态，如，关注中，取消关注等
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user.STATUS
     *
     * @mbg.generated 2018-07-20 18:10:04
     */
    private String status;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getWhich() {
        return which;
    }

    public void setWhich(String which) {
        this.which = which;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getUnionid() {
        return unionid;
    }

    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getHeadImageUrl() {
        return headImageUrl;
    }

    public void setHeadImageUrl(String headImageUrl) {
        this.headImageUrl = headImageUrl;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getPrecisions() {
        return precisions;
    }

    public void setPrecisions(String precisions) {
        this.precisions = precisions;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getHowFrom() {
        return howFrom;
    }

    public void setHowFrom(String howFrom) {
        this.howFrom = howFrom;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public com.feihua.wechat.common.api.ApiWeixinUserPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.wechat.common.api.ApiWeixinUserPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", type=").append(type);
        sb.append(", which=").append(which);
        sb.append(", openid=").append(openid);
        sb.append(", unionid=").append(unionid);
        sb.append(", nickname=").append(nickname);
        sb.append(", city=").append(city);
        sb.append(", province=").append(province);
        sb.append(", country=").append(country);
        sb.append(", headImageUrl=").append(headImageUrl);
        sb.append(", language=").append(language);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", precisions=").append(precisions);
        sb.append(", gender=").append(gender);
        sb.append(", location=").append(location);
        sb.append(", howFrom=").append(howFrom);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}