package com.feihua.framework.base.modules.user.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-04-19 14:30:11
 *
 * This class corresponds to the database table base_user
 * @mbg.generated do_not_delete_during_merge 2018-04-19 14:30:11
*/
public class BaseUserPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.SERIAL_NO
     *
     * @mbg.generated 2018-04-19 14:30:11
     */
    private String serialNo;

    /**
     * Database Column Remarks:
     *   头像，图片路径信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.PHOTO
     *
     * @mbg.generated 2018-04-19 14:30:11
     */
    private String photo;

    /**
     * Database Column Remarks:
     *   昵称，姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.NICKNAME
     *
     * @mbg.generated 2018-04-19 14:30:11
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   性别，male=男；female=女；unknown=未知；secret=保密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.GENDER
     *
     * @mbg.generated 2018-04-19 14:30:11
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   锁定状态，N=未锁定；Y=锁定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.LOCKED
     *
     * @mbg.generated 2018-04-19 14:30:11
     */
    private String locked;

    public String getSerialNo() {
        return serialNo;
    }

    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getLocked() {
        return locked;
    }

    public void setLocked(String locked) {
        this.locked = locked;
    }

    public com.feihua.framework.base.modules.user.api.ApiBaseUserPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.base.modules.user.api.ApiBaseUserPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serialNo=").append(serialNo);
        sb.append(", photo=").append(photo);
        sb.append(", nickname=").append(nickname);
        sb.append(", gender=").append(gender);
        sb.append(", locked=").append(locked);
        sb.append("]");
        return sb.toString();
    }
}