package com.feihua.framework.base.modules.user.po;

import feihua.jdbc.api.pojo.BasePo;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-18 09:24:16
 * Database Table Remarks:
 *   用户最后访问时间表，同一个用户同一个客户端只有一条数据
 *
 * This class corresponds to the database table base_user_access_lasttime
 * @mbg.generated do_not_delete_during_merge 2019-06-18 09:24:16
*/
public class BaseUserAccessLasttimePo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_access_lasttime.user_id
     *
     * @mbg.generated 2019-06-18 09:24:16
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_access_lasttime.user_nickname
     *
     * @mbg.generated 2019-06-18 09:24:16
     */
    private String userNickname;

    /**
     * Database Column Remarks:
     *   客户端id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_access_lasttime.client_id
     *
     * @mbg.generated 2019-06-18 09:24:16
     */
    private String clientId;

    /**
     * Database Column Remarks:
     *   客户端名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_access_lasttime.client_name
     *
     * @mbg.generated 2019-06-18 09:24:16
     */
    private String clientName;

    /**
     * Database Column Remarks:
     *   访问ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_access_lasttime.access_ip
     *
     * @mbg.generated 2019-06-18 09:24:16
     */
    private String accessIp;

    /**
     * Database Column Remarks:
     *   最后访问时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_access_lasttime.access_lasttime
     *
     * @mbg.generated 2019-06-18 09:24:16
     */
    private Date accessLasttime;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserNickname() {
        return userNickname;
    }

    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getAccessIp() {
        return accessIp;
    }

    public void setAccessIp(String accessIp) {
        this.accessIp = accessIp;
    }

    public Date getAccessLasttime() {
        return accessLasttime;
    }

    public void setAccessLasttime(Date accessLasttime) {
        this.accessLasttime = accessLasttime;
    }

    public com.feihua.framework.base.modules.user.api.ApiBaseUserAccessLasttimePoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.base.modules.user.api.ApiBaseUserAccessLasttimePoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userNickname=").append(userNickname);
        sb.append(", clientId=").append(clientId);
        sb.append(", clientName=").append(clientName);
        sb.append(", accessIp=").append(accessIp);
        sb.append(", accessLasttime=").append(accessLasttime);
        sb.append("]");
        return sb.toString();
    }
}