package com.feihua.framework.base.modules.message.api;

import com.feihua.framework.base.modules.message.dto.BaseMessageTargetClientDto;
import com.feihua.framework.base.modules.message.po.BaseMessageTargetClientPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-31 12:43:49
 */
public interface ApiBaseMessageTargetClientPoService extends feihua.jdbc.api.service.ApiBaseService<BaseMessageTargetClientPo, BaseMessageTargetClientDto, String> {
}