package com.feihua.framework.cms.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-11-09 16:45:29
 *
 * This class corresponds to the database table cms_channel
 * @mbg.generated do_not_delete_during_merge 2018-11-09 16:45:29
*/
public class CmsChannelPo extends feihua.jdbc.api.pojo.BaseTreePo<String> {
    /**
     * Database Column Remarks:
     *   栏目名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.NAME
     *
     * @mbg.generated 2018-11-09 16:45:29
     */
    private String name;

    /**
     * Database Column Remarks:
     *   访问路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.PATH
     *
     * @mbg.generated 2018-11-09 16:45:29
     */
    private String path;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.SEQUENCE
     *
     * @mbg.generated 2018-11-09 16:45:29
     */
    private Integer sequence;

    /**
     * Database Column Remarks:
     *   站点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.SITE_ID
     *
     * @mbg.generated 2018-11-09 16:45:29
     */
    private String siteId;

    /**
     * Database Column Remarks:
     *   页面访问量,页面点击次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.PV
     *
     * @mbg.generated 2018-11-09 16:45:29
     */
    private Integer pv;

    /**
     * Database Column Remarks:
     *   页面访问量，独立IP数，页面访问ip数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.IV
     *
     * @mbg.generated 2018-11-09 16:45:29
     */
    private Integer iv;

    /**
     * Database Column Remarks:
     *   页面访问量，独立电脑客户端数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.UV
     *
     * @mbg.generated 2018-11-09 16:45:29
     */
    private Integer uv;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public Integer getPv() {
        return pv;
    }

    public void setPv(Integer pv) {
        this.pv = pv;
    }

    public Integer getIv() {
        return iv;
    }

    public void setIv(Integer iv) {
        this.iv = iv;
    }

    public Integer getUv() {
        return uv;
    }

    public void setUv(Integer uv) {
        this.uv = uv;
    }

    public com.feihua.framework.cms.api.ApiCmsChannelPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.cms.api.ApiCmsChannelPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", path=").append(path);
        sb.append(", sequence=").append(sequence);
        sb.append(", siteId=").append(siteId);
        sb.append(", pv=").append(pv);
        sb.append(", iv=").append(iv);
        sb.append(", uv=").append(uv);
        sb.append("]");
        return sb.toString();
    }
}