package com.feihua.framework.cms.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-11-09 16:53:22
 *
 * This class corresponds to the database table cms_channel_page_view
 * @mbg.generated do_not_delete_during_merge 2018-11-09 16:53:22
*/
public class CmsChannelPageViewPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   栏目id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel_page_view.CHANNEL_ID
     *
     * @mbg.generated 2018-11-09 16:53:22
     */
    private String channelId;

    /**
     * Database Column Remarks:
     *   站点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel_page_view.SITE_ID
     *
     * @mbg.generated 2018-11-09 16:53:22
     */
    private String siteId;

    /**
     * Database Column Remarks:
     *   cookie
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel_page_view.COOKIE
     *
     * @mbg.generated 2018-11-09 16:53:22
     */
    private String cookie;

    /**
     * Database Column Remarks:
     *   IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel_page_view.HOST
     *
     * @mbg.generated 2018-11-09 16:53:22
     */
    private String host;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public String getCookie() {
        return cookie;
    }

    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

    public String getHost() {
        return host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public com.feihua.framework.cms.api.ApiCmsChannelPageViewPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.cms.api.ApiCmsChannelPageViewPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", channelId=").append(channelId);
        sb.append(", siteId=").append(siteId);
        sb.append(", cookie=").append(cookie);
        sb.append(", host=").append(host);
        sb.append("]");
        return sb.toString();
    }
}