package com.feihua.framework.cms.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-25 13:50:27
 * Database Table Remarks:
 *   内容视频表
 *
 * This class corresponds to the database table cms_content_video
 * @mbg.generated do_not_delete_during_merge 2018-12-25 13:50:27
*/
public class CmsContentVideoPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   站点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.SITE_ID
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String siteId;

    /**
     * Database Column Remarks:
     *   内容id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.CONTENT_ID
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String contentId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.FILENAME
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String filename;

    /**
     * Database Column Remarks:
     *   视频地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.URL
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String url;

    /**
     * Database Column Remarks:
     *   视频类型，扩展名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.EXT
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String ext;

    /**
     * Database Column Remarks:
     *   视频类型，字典，
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.TYPE
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String type;

    /**
     * Database Column Remarks:
     *   下载次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.DWONLOAD_NUM
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private Integer dwonloadNum;

    /**
     * Database Column Remarks:
     *   大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.SIZE
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String size;

    /**
     * Database Column Remarks:
     *   附件描述信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.DESCRIPTION
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String description;

    /**
     * Database Column Remarks:
     *   图片url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.IMAGE_URL
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String imageUrl;

    /**
     * Database Column Remarks:
     *   图片描述信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.IMAGE_DES
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String imageDes;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.SEQUENCE
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private Integer sequence;

    /**
     * Database Column Remarks:
     *   时长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.DURATION
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String duration;

    /**
     * Database Column Remarks:
     *   播放器，字典
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.PLAYER
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String player;

    /**
     * Database Column Remarks:
     *   演唱 、演说、主讲人、导演
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.DIRECTOR
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String director;

    /**
     * Database Column Remarks:
     *   主演
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.PERFORMER
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String performer;

    /**
     * Database Column Remarks:
     *   语言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.LANGUAGE
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String language;

    /**
     * Database Column Remarks:
     *   国家/地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.REGION
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String region;

    /**
     * Database Column Remarks:
     *   总季数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.SEASON_COUNT
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private Integer seasonCount;

    /**
     * Database Column Remarks:
     *   当前第几季
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.SEASON
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private Integer season;

    /**
     * Database Column Remarks:
     *   总集数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.SPISODE_COUNT
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private Integer spisodeCount;

    /**
     * Database Column Remarks:
     *   当前第几集
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.SPISODE
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private Integer spisode;

    /**
     * Database Column Remarks:
     *   年，2018
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_video.YEARS
     *
     * @mbg.generated 2018-12-25 13:50:27
     */
    private String years;

    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public String getContentId() {
        return contentId;
    }

    public void setContentId(String contentId) {
        this.contentId = contentId;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getDwonloadNum() {
        return dwonloadNum;
    }

    public void setDwonloadNum(Integer dwonloadNum) {
        this.dwonloadNum = dwonloadNum;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getImageDes() {
        return imageDes;
    }

    public void setImageDes(String imageDes) {
        this.imageDes = imageDes;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getPlayer() {
        return player;
    }

    public void setPlayer(String player) {
        this.player = player;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public String getPerformer() {
        return performer;
    }

    public void setPerformer(String performer) {
        this.performer = performer;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public Integer getSeasonCount() {
        return seasonCount;
    }

    public void setSeasonCount(Integer seasonCount) {
        this.seasonCount = seasonCount;
    }

    public Integer getSeason() {
        return season;
    }

    public void setSeason(Integer season) {
        this.season = season;
    }

    public Integer getSpisodeCount() {
        return spisodeCount;
    }

    public void setSpisodeCount(Integer spisodeCount) {
        this.spisodeCount = spisodeCount;
    }

    public Integer getSpisode() {
        return spisode;
    }

    public void setSpisode(Integer spisode) {
        this.spisode = spisode;
    }

    public String getYears() {
        return years;
    }

    public void setYears(String years) {
        this.years = years;
    }

    public com.feihua.framework.cms.api.ApiCmsContentVideoPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.cms.api.ApiCmsContentVideoPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", siteId=").append(siteId);
        sb.append(", contentId=").append(contentId);
        sb.append(", filename=").append(filename);
        sb.append(", url=").append(url);
        sb.append(", ext=").append(ext);
        sb.append(", type=").append(type);
        sb.append(", dwonloadNum=").append(dwonloadNum);
        sb.append(", size=").append(size);
        sb.append(", description=").append(description);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", imageDes=").append(imageDes);
        sb.append(", sequence=").append(sequence);
        sb.append(", duration=").append(duration);
        sb.append(", player=").append(player);
        sb.append(", director=").append(director);
        sb.append(", performer=").append(performer);
        sb.append(", language=").append(language);
        sb.append(", region=").append(region);
        sb.append(", seasonCount=").append(seasonCount);
        sb.append(", season=").append(season);
        sb.append(", spisodeCount=").append(spisodeCount);
        sb.append(", spisode=").append(spisode);
        sb.append(", years=").append(years);
        sb.append("]");
        return sb.toString();
    }
}