package com.feihua.framework.cms.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-25 16:19:41
 * Database Table Remarks:
 *   内容音频表
 *
 * This class corresponds to the database table cms_content_audio
 * @mbg.generated do_not_delete_during_merge 2018-12-25 16:19:41
*/
public class CmsContentAudioPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   站点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.SITE_ID
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String siteId;

    /**
     * Database Column Remarks:
     *   内容id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.CONTENT_ID
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String contentId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.FILENAME
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String filename;

    /**
     * Database Column Remarks:
     *   音频地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.URL
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String url;

    /**
     * Database Column Remarks:
     *   音频类型，扩展名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.EXT
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String ext;

    /**
     * Database Column Remarks:
     *   音频类型，字典，
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.TYPE
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String type;

    /**
     * Database Column Remarks:
     *   下载次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.DWONLOAD_NUM
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private Integer dwonloadNum;

    /**
     * Database Column Remarks:
     *   大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.SIZE
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String size;

    /**
     * Database Column Remarks:
     *   附件描述信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.DESCRIPTION
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String description;

    /**
     * Database Column Remarks:
     *   图片url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.IMAGE_URL
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String imageUrl;

    /**
     * Database Column Remarks:
     *   图片描述信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.IMAGE_DES
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String imageDes;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.SEQUENCE
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private Integer sequence;

    /**
     * Database Column Remarks:
     *   时长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.DURATION
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String duration;

    /**
     * Database Column Remarks:
     *   专辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.ALBUM
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String album;

    /**
     * Database Column Remarks:
     *   国家/地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.REGION
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String region;

    /**
     * Database Column Remarks:
     *   播放器，字典
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.PLAYER
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String player;

    /**
     * Database Column Remarks:
     *   演唱 、演说、主讲人、导演
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.DIRECTOR
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String director;

    /**
     * Database Column Remarks:
     *   主演
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.PERFORMER
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String performer;

    /**
     * Database Column Remarks:
     *   语言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.LANGUAGE
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String language;

    /**
     * Database Column Remarks:
     *   年代
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.YEARS
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String years;

    /**
     * Database Column Remarks:
     *   音频字幕，歌词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_audio.LRC
     *
     * @mbg.generated 2018-12-25 16:19:41
     */
    private String lrc;

    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public String getContentId() {
        return contentId;
    }

    public void setContentId(String contentId) {
        this.contentId = contentId;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getDwonloadNum() {
        return dwonloadNum;
    }

    public void setDwonloadNum(Integer dwonloadNum) {
        this.dwonloadNum = dwonloadNum;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getImageDes() {
        return imageDes;
    }

    public void setImageDes(String imageDes) {
        this.imageDes = imageDes;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getPlayer() {
        return player;
    }

    public void setPlayer(String player) {
        this.player = player;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public String getPerformer() {
        return performer;
    }

    public void setPerformer(String performer) {
        this.performer = performer;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getYears() {
        return years;
    }

    public void setYears(String years) {
        this.years = years;
    }

    public String getLrc() {
        return lrc;
    }

    public void setLrc(String lrc) {
        this.lrc = lrc;
    }

    public com.feihua.framework.cms.api.ApiCmsContentAudioPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.cms.api.ApiCmsContentAudioPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", siteId=").append(siteId);
        sb.append(", contentId=").append(contentId);
        sb.append(", filename=").append(filename);
        sb.append(", url=").append(url);
        sb.append(", ext=").append(ext);
        sb.append(", type=").append(type);
        sb.append(", dwonloadNum=").append(dwonloadNum);
        sb.append(", size=").append(size);
        sb.append(", description=").append(description);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", imageDes=").append(imageDes);
        sb.append(", sequence=").append(sequence);
        sb.append(", duration=").append(duration);
        sb.append(", album=").append(album);
        sb.append(", region=").append(region);
        sb.append(", player=").append(player);
        sb.append(", director=").append(director);
        sb.append(", performer=").append(performer);
        sb.append(", language=").append(language);
        sb.append(", years=").append(years);
        sb.append(", lrc=").append(lrc);
        sb.append("]");
        return sb.toString();
    }
}