package com.feihua.framework.cms.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-13 10:59:21
 * Database Table Remarks:
 *   内容分类
 *
 * This class corresponds to the database table cms_content_category
 * @mbg.generated do_not_delete_during_merge 2018-12-13 10:59:21
*/
public class CmsContentCategoryPo extends feihua.jdbc.api.pojo.BaseTreePo<String> {
    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_category.NAME
     *
     * @mbg.generated 2018-12-13 10:59:21
     */
    private String name;

    /**
     * Database Column Remarks:
     *   站点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_category.SITE_ID
     *
     * @mbg.generated 2018-12-13 10:59:21
     */
    private String siteId;

    /**
     * Database Column Remarks:
     *   栏目id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_category.CHANNEL_ID
     *
     * @mbg.generated 2018-12-13 10:59:21
     */
    private String channelId;

    /**
     * Database Column Remarks:
     *   分类描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_category.DESCRIPTION
     *
     * @mbg.generated 2018-12-13 10:59:21
     */
    private String description;

    /**
     * Database Column Remarks:
     *   图片url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_category.IMAGE_URL
     *
     * @mbg.generated 2018-12-13 10:59:21
     */
    private String imageUrl;

    /**
     * Database Column Remarks:
     *   图片描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_category.IMAGE_DES
     *
     * @mbg.generated 2018-12-13 10:59:21
     */
    private String imageDes;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content_category.SEQUENCE
     *
     * @mbg.generated 2018-12-13 10:59:21
     */
    private Integer sequence;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getImageDes() {
        return imageDes;
    }

    public void setImageDes(String imageDes) {
        this.imageDes = imageDes;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public com.feihua.framework.cms.api.ApiCmsContentCategoryPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.cms.api.ApiCmsContentCategoryPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", siteId=").append(siteId);
        sb.append(", channelId=").append(channelId);
        sb.append(", description=").append(description);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", imageDes=").append(imageDes);
        sb.append(", sequence=").append(sequence);
        sb.append("]");
        return sb.toString();
    }
}