package com.feihua.framework.cms.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-01-17 14:00:41
 * Database Table Remarks:
 *   调查问题表
 *
 * This class corresponds to the database table cms_question
 * @mbg.generated do_not_delete_during_merge 2019-01-17 14:00:41
*/
public class CmsQuestionPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   调查ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_question.SURVEY_ID
     *
     * @mbg.generated 2019-01-17 14:00:41
     */
    private String surveyId;

    /**
     * Database Column Remarks:
     *   问卷调查问题主题题干
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_question.NAME
     *
     * @mbg.generated 2019-01-17 14:00:41
     */
    private String name;

    /**
     * Database Column Remarks:
     *   问题类型（单选：radio，多选：checkbox，文本（问答题）：text）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_question.TYPE
     *
     * @mbg.generated 2019-01-17 14:00:41
     */
    private String type;

    /**
     * Database Column Remarks:
     *   是否换行（Y/N）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_question.BR
     *
     * @mbg.generated 2019-01-17 14:00:41
     */
    private String br;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_question.SEQUENCE
     *
     * @mbg.generated 2019-01-17 14:00:41
     */
    private Integer sequence;

    public String getSurveyId() {
        return surveyId;
    }

    public void setSurveyId(String surveyId) {
        this.surveyId = surveyId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getBr() {
        return br;
    }

    public void setBr(String br) {
        this.br = br;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public com.feihua.framework.cms.api.ApiCmsQuestionPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.cms.api.ApiCmsQuestionPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", surveyId=").append(surveyId);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", br=").append(br);
        sb.append(", sequence=").append(sequence);
        sb.append("]");
        return sb.toString();
    }
}