package com.feihua.framework.cms.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-05 16:54:07
 * Database Table Remarks:
 *   cms站点表
 *
 * This class corresponds to the database table cms_site
 * @mbg.generated do_not_delete_during_merge 2018-12-05 16:54:07
*/
public class CmsSitePo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.NAME
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private String name;

    /**
     * Database Column Remarks:
     *   域名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.DOMAIN
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private String domain;

    /**
     * Database Column Remarks:
     *   站点访问上下文路径，主要应用于动态页访问，可以实现在一个域名下区分不同的站点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.PATH
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private String path;

    /**
     * Database Column Remarks:
     *   路径，站点模板存放路径，pc默认default,移动端默认mobile,站点首页模板默认index.html
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.TEMPLATE_PATH
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private String templatePath;

    /**
     * Database Column Remarks:
     *   站点首页模板默认index.html
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.TEMPLATE
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private String template;

    /**
     * Database Column Remarks:
     *   站点静态页存放路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.STATIC_PATH
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private String staticPath;

    /**
     * Database Column Remarks:
     *   站点部署路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.DEPLOY_PATH
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private String deployPath;

    /**
     * Database Column Remarks:
     *   是否主站，Y=是，N=否，同一个域名即domain字段下，只能有一个主站
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.IS_MAIN
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private String isMain;

    /**
     * Database Column Remarks:
     *   页面访问量,页面点击次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.PV
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private Integer pv;

    /**
     * Database Column Remarks:
     *   页面访问量，独立IP数，页面访问ip数,一天之内相同IP地址只被计算一次
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.IV
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private Integer iv;

    /**
     * Database Column Remarks:
     *   页面访问量，独立电脑客户端,一天之内相同cookie的访问只被计算1次
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_site.UV
     *
     * @mbg.generated 2018-12-05 16:54:07
     */
    private Integer uv;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getTemplatePath() {
        return templatePath;
    }

    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath;
    }

    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public String getStaticPath() {
        return staticPath;
    }

    public void setStaticPath(String staticPath) {
        this.staticPath = staticPath;
    }

    public String getDeployPath() {
        return deployPath;
    }

    public void setDeployPath(String deployPath) {
        this.deployPath = deployPath;
    }

    public String getIsMain() {
        return isMain;
    }

    public void setIsMain(String isMain) {
        this.isMain = isMain;
    }

    public Integer getPv() {
        return pv;
    }

    public void setPv(Integer pv) {
        this.pv = pv;
    }

    public Integer getIv() {
        return iv;
    }

    public void setIv(Integer iv) {
        this.iv = iv;
    }

    public Integer getUv() {
        return uv;
    }

    public void setUv(Integer uv) {
        this.uv = uv;
    }

    public com.feihua.framework.cms.api.ApiCmsSitePoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.cms.api.ApiCmsSitePoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", domain=").append(domain);
        sb.append(", path=").append(path);
        sb.append(", templatePath=").append(templatePath);
        sb.append(", template=").append(template);
        sb.append(", staticPath=").append(staticPath);
        sb.append(", deployPath=").append(deployPath);
        sb.append(", isMain=").append(isMain);
        sb.append(", pv=").append(pv);
        sb.append(", iv=").append(iv);
        sb.append(", uv=").append(uv);
        sb.append("]");
        return sb.toString();
    }
}