package com.feihua.framework.base.modules.file.dto;

import feihua.jdbc.api.pojo.BaseConditionDto;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_file
 *
 * @mbg.generated 2018-04-16 15:43:17
*/
public class SearchBaseFilesConditionDto extends BaseConditionDto {

    private String name;

    private String type;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}