package com.wwd.service.impl;

import com.wwd.service.mapper.WwdUserAreaPoMapper;
import com.wwd.service.modules.wwd.api.ApiWwdUserAreaPoService;
import com.wwd.service.modules.wwd.dto.WwdUserAreaDto;
import com.wwd.service.modules.wwd.po.WwdUserAreaPo;
import feihua.jdbc.api.pojo.BasePo;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-04-25 11:24:07
 */
@Service
public class ApiWwdUserAreaPoServiceImpl extends ApiBaseServiceImpl<WwdUserAreaPo, WwdUserAreaDto, String> implements ApiWwdUserAreaPoService {
    @Autowired
    WwdUserAreaPoMapper wwdUserAreaPoMapper;

    public ApiWwdUserAreaPoServiceImpl() {
        super(WwdUserAreaDto.class);
    }

    @Transactional( propagation = Propagation.SUPPORTS, readOnly = true )
    @Override
    public WwdUserAreaDto selectByWwdUserId(String wwdUserId) {
        WwdUserAreaPo wwdUserAreaPo = new WwdUserAreaPo();
        wwdUserAreaPo.setWwdUserId(wwdUserId);
        wwdUserAreaPo.setDelFlag(BasePo.YesNo.N.name());
        return this.selectOne(wwdUserAreaPo);
    }

    @Override
    public WwdUserAreaDto wrapDto(WwdUserAreaPo po) {
        if (po == null) {
            return null;
        }
        WwdUserAreaDto wwdUserAreaDto = new WwdUserAreaDto();
        wwdUserAreaDto.setWwdUserId(po.getWwdUserId());
        wwdUserAreaDto.setNowTownId(po.getNowTownId());
        wwdUserAreaDto.setHomeTownId(po.getHomeTownId());
        wwdUserAreaDto.setNowCityId(po.getNowCityId());
        wwdUserAreaDto.setDataType(po.getDataType());
        wwdUserAreaDto.setDataUserId(po.getDataUserId());
        wwdUserAreaDto.setUpdateAt(po.getUpdateAt());
        wwdUserAreaDto.setId(po.getId());
        wwdUserAreaDto.setHomeCityId(po.getHomeCityId());
        wwdUserAreaDto.setDataAreaId(po.getDataAreaId());
        wwdUserAreaDto.setNowCityName(po.getNowCityName());
        wwdUserAreaDto.setNowProvinceName(po.getNowProvinceName());
        wwdUserAreaDto.setNowDistrictName(po.getNowDistrictName());
        wwdUserAreaDto.setHomeProvinceName(po.getHomeProvinceName());
        wwdUserAreaDto.setNowProvinceId(po.getNowProvinceId());
        wwdUserAreaDto.setNowDistrictId(po.getNowDistrictId());
        wwdUserAreaDto.setHomeDistrictId(po.getHomeDistrictId());
        wwdUserAreaDto.setNowTownName(po.getNowTownName());
        wwdUserAreaDto.setHomeCityName(po.getHomeCityName());
        wwdUserAreaDto.setHomeProvinceId(po.getHomeProvinceId());
        wwdUserAreaDto.setHomeDistrictName(po.getHomeDistrictName());
        wwdUserAreaDto.setDataOfficeId(po.getDataOfficeId());
        wwdUserAreaDto.setHomeTownName(po.getHomeTownName());
        return wwdUserAreaDto;
    }
}