package com.wwd.service.impl;

import com.github.pagehelper.Page;
import com.wwd.service.modules.wwd.api.ApiWwdUserCardService;
import com.wwd.service.modules.wwd.dto.WwdUserCardDto;
import com.wwd.service.modules.wwd.po.WwdUserCard;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-11-01 10:40:46
 */
@Service
public class ApiWwdUserCardServiceImpl extends ApiBaseServiceImpl<WwdUserCard, WwdUserCardDto, String> implements ApiWwdUserCardService {
    @Autowired
    com.wwd.service.mapper.WwdUserCardMapper WwdUserCardMapper;

    public ApiWwdUserCardServiceImpl() {
        super(WwdUserCardDto.class);
    }

    @Override
    public PageResultDto<WwdUserCardDto> searchWwdUserCardsDsf(com.wwd.service.modules.wwd.dto.SearchWwdUserCardsConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.wwd.service.modules.wwd.dto.WwdUserCardDto> list = this.wrapDtos(WwdUserCardMapper.searchWwdUserCards(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }
}