package com.feihua.framework.rest.modules.rel.dto;

import java.util.Date;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_post_role_rel
 *
 * @mbg.generated 2019-06-12 14:06:12
*/
public class PostBindRolesFormDto {

    List<String> roleIds;

    public List<String> getRoleIds() {
        return roleIds;
    }

    public void setRoleIds(List<String> roleIds) {
        this.roleIds = roleIds;
    }
}