package com.feihua.framework.rest.modules.rel.dto;

import com.feihua.framework.rest.dto.UpdateFormDto;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_user_post_rel
 *
 * @mbg.generated 2019-06-12 14:56:32
*/
public class PostBindUsersFormDto extends UpdateFormDto {

    List<String> userIds;

    public List<String> getUserIds() {
        return userIds;
    }

    public void setUserIds(List<String> userIds) {
        this.userIds = userIds;
    }
}