package com.wwd.service.modules.wwd.api;

import com.wwd.service.modules.wwd.dto.SearchWwdUserEnjoysConditionDto;
import com.wwd.service.modules.wwd.dto.WwdUserEnjoyDto;
import com.wwd.service.modules.wwd.po.WwdUserEnjoyPo;
import feihua.jdbc.api.pojo.PageAndOrderbyParamDto;
import feihua.jdbc.api.pojo.PageResultDto;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-05-19 15:53:51
 */
public interface ApiWwdUserEnjoyPoService extends feihua.jdbc.api.service.ApiBaseService<WwdUserEnjoyPo, WwdUserEnjoyDto, String> {
    PageResultDto<WwdUserEnjoyDto> searchWwdUserEnjoysDsf(SearchWwdUserEnjoysConditionDto dto, PageAndOrderbyParamDto pageAndOrderbyParamDto);

    /**
     * 查询我有意思的人
     * @param wwdUserId
     * @return
     */
    List<WwdUserEnjoyDto> selectByWwdUserId(String wwdUserId);

    /**
     * 查询我有意思的人分页
     * @param wwdUserId
     * @param pageAndOrderbyParamDto
     * @return
     */
    PageResultDto<WwdUserEnjoyDto> selectByWwdUserId(String wwdUserId, PageAndOrderbyParamDto pageAndOrderbyParamDto);

    /**
     * 查询对我有意思的人
     * @param enjoyedWwdUserId
     * @return
     */
    List<WwdUserEnjoyDto> selectByEnjoyedWwdUserId(String enjoyedWwdUserId);

    /**
     * 查询对我有意思的人分页
     * @param enjoyedWwdUserId
     * @param pageAndOrderbyParamDto
     * @return
     */
    PageResultDto<WwdUserEnjoyDto> selectByEnjoyedWwdUserId(String enjoyedWwdUserId, PageAndOrderbyParamDto pageAndOrderbyParamDto);

    /**
     * 查询我有意思且也对我有意思的人
     * @param enjoyedWwdUserId
     * @return
     */
    List<WwdUserEnjoyDto> selectEnjoyedByWwdUserId(String enjoyedWwdUserId);

    /**
     * 分页查询我有意思且也对我有意思的人
     * @param wwdUserId 主体用户id
     * @param pageAndOrderbyParamDto
     * @return
     */
    PageResultDto<WwdUserEnjoyDto> selectEnjoyedByWwdUserId(String wwdUserId, PageAndOrderbyParamDto pageAndOrderbyParamDto);

    /**
     * 查询 wwdUserId 是否对 enjoyedWwdUserId有意思
     * @param wwdUserId
     * @param enjoyedWwdUserId
     * @return 存在数据即有意思
     */
    public WwdUserEnjoyDto selectEnjoyedFromTo(String wwdUserId, String enjoyedWwdUserId);
}