package com.feihua.framework.message.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-07 11:35:30
 * Database Table Remarks:
 *   消息三方内容表
 *
 * This class corresponds to the database table base_message_third
 * @mbg.generated do_not_delete_during_merge 2019-05-07 11:35:30
*/
public class BaseMessageThirdPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   消息id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_message_third.message_id
     *
     * @mbg.generated 2019-05-07 11:35:30
     */
    private String messageId;

    /**
     * Database Column Remarks:
     *   三方的类型，标识是公众平台还是小程序等等
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_message_third.third_type
     *
     * @mbg.generated 2019-05-07 11:35:30
     */
    private String thirdType;

    /**
     * Database Column Remarks:
     *   三方的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_message_third.third_id
     *
     * @mbg.generated 2019-05-07 11:35:30
     */
    private String thirdId;

    /**
     * Database Column Remarks:
     *   三方模板id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_message_third.third_template_id
     *
     * @mbg.generated 2019-05-07 11:35:30
     */
    private String thirdTemplateId;

    /**
     * Database Column Remarks:
     *   三方模板内容，不同三方配置不同
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_message_third.third_template_content
     *
     * @mbg.generated 2019-05-07 11:35:30
     */
    private String thirdTemplateContent;

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getThirdType() {
        return thirdType;
    }

    public void setThirdType(String thirdType) {
        this.thirdType = thirdType;
    }

    public String getThirdId() {
        return thirdId;
    }

    public void setThirdId(String thirdId) {
        this.thirdId = thirdId;
    }

    public String getThirdTemplateId() {
        return thirdTemplateId;
    }

    public void setThirdTemplateId(String thirdTemplateId) {
        this.thirdTemplateId = thirdTemplateId;
    }

    public String getThirdTemplateContent() {
        return thirdTemplateContent;
    }

    public void setThirdTemplateContent(String thirdTemplateContent) {
        this.thirdTemplateContent = thirdTemplateContent;
    }

    public com.feihua.framework.message.api.ApiBaseMessageThirdPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.message.api.ApiBaseMessageThirdPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", messageId=").append(messageId);
        sb.append(", thirdType=").append(thirdType);
        sb.append(", thirdId=").append(thirdId);
        sb.append(", thirdTemplateId=").append(thirdTemplateId);
        sb.append(", thirdTemplateContent=").append(thirdTemplateContent);
        sb.append("]");
        return sb.toString();
    }
}