package com.feihua.framework.spider.mapper;

import com.feihua.framework.spider.po.SpiderContentResultPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-19 17:19:18
 */
public interface SpiderContentResultPoMapper extends feihua.jdbc.api.dao.CrudDao<SpiderContentResultPo, String> {

}