package com.feihua.framework.spider.mapper;

import com.feihua.framework.spider.po.SpiderResultUrlsPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-12-19 21:08:09
 */
public interface SpiderResultUrlsPoMapper extends feihua.jdbc.api.dao.CrudDao<SpiderResultUrlsPo, String> {
}