package com.feihua.framework.spider.rest.dto;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table spider_config_content
 *
 * @mbg.generated 2018-12-19 17:17:58
*/
public class AddSpiderConfigContentFormDto {

    private String configSourceId;

    private String contentKey;

    private String contentValueSelector;

    private String contentKeyDes;

    public String getConfigSourceId() {
        return configSourceId;
    }

    public void setConfigSourceId(String configSourceId) {
        this.configSourceId = configSourceId;
    }

    public String getContentKey() {
        return contentKey;
    }

    public void setContentKey(String contentKey) {
        this.contentKey = contentKey;
    }

    public String getContentValueSelector() {
        return contentValueSelector;
    }

    public void setContentValueSelector(String contentValueSelector) {
        this.contentValueSelector = contentValueSelector;
    }

    public String getContentKeyDes() {
        return contentKeyDes;
    }

    public void setContentKeyDes(String contentKeyDes) {
        this.contentKeyDes = contentKeyDes;
    }
}