package com.feihua.framework.base.modules.role.api;

import com.feihua.framework.base.modules.role.dto.BaseRoleDataScopeDefineSelfDto;
import com.feihua.framework.base.modules.role.dto.BaseRoleDataScopeDefineSelfDto;
import com.feihua.framework.base.modules.role.po.BaseRoleDataScopeDefineSelfPo;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-03-19 19:28:24
 */
public interface ApiBaseRoleDataScopeDefineSelfPoService extends feihua.jdbc.api.service.ApiBaseService<BaseRoleDataScopeDefineSelfPo, BaseRoleDataScopeDefineSelfDto, String> {


    /**
     * 插入角色数据范围定义与角色自定义的关系
     * @param roleIds
     * @param roleDataScopeDefineId
     * @param currentUserId 当前登录用户
     * @return
     */
    public int insertRoleSelf(List<String> roleIds, String roleDataScopeDefineId, String currentUserId);

    /**
     * 根据角色数据范围定义id删除自定义关系
     * @param roleDataScopeDefineId
     * @param currentUserId
     * @return
     */
    public int deleteRoleSelfByRoleDataScopeDefineId(String roleDataScopeDefineId, String currentUserId);

    /**
     * 根据角色数据范围定义id查询自定义设置的角色ids
     * @param roleDataScopeDefineId
     * @return
     */
    public List<BaseRoleDataScopeDefineSelfDto> selectByRoleDataScopeDefineId(String roleDataScopeDefineId);
}