package com.feihua.framework.statistic.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-23 09:21:26
 * Database Table Remarks:
 *   用户客户端统计
 *
 * This class corresponds to the database table statistic_user_client_count_history
 * @mbg.generated do_not_delete_during_merge 2019-04-23 09:21:26
*/
public class StatisticUserClientCountHistoryPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   客户端id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.client_id
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private String clientId;

    /**
     * Database Column Remarks:
     *   客户端编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.client_code
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private String clientCode;

    /**
     * Database Column Remarks:
     *   客户端名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.client_name
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private String clientName;

    /**
     * Database Column Remarks:
     *   批次号，同一个批次号标识是一组数组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.batch_no
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private String batchNo;

    /**
     * Database Column Remarks:
     *   用户总数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.all_num
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private Integer allNum;

    /**
     * Database Column Remarks:
     *   性别男数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.male_num
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private Integer maleNum;

    /**
     * Database Column Remarks:
     *   性别女数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.female_num
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private Integer femaleNum;

    /**
     * Database Column Remarks:
     *   性别其它数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.gender_other_num
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private Integer genderOtherNum;

    /**
     * Database Column Remarks:
     *   在线用户数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.online_all_num
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private Integer onlineAllNum;

    /**
     * Database Column Remarks:
     *   在线性别男用户数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.online_male_num
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private Integer onlineMaleNum;

    /**
     * Database Column Remarks:
     *   在线性别女用户数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.online_female_num
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private Integer onlineFemaleNum;

    /**
     * Database Column Remarks:
     *   在线性别其它用户数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_user_client_count_history.online_gender_other_num
     *
     * @mbg.generated 2019-04-23 09:21:26
     */
    private Integer onlineGenderOtherNum;

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getClientCode() {
        return clientCode;
    }

    public void setClientCode(String clientCode) {
        this.clientCode = clientCode;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public Integer getAllNum() {
        return allNum;
    }

    public void setAllNum(Integer allNum) {
        this.allNum = allNum;
    }

    public Integer getMaleNum() {
        return maleNum;
    }

    public void setMaleNum(Integer maleNum) {
        this.maleNum = maleNum;
    }

    public Integer getFemaleNum() {
        return femaleNum;
    }

    public void setFemaleNum(Integer femaleNum) {
        this.femaleNum = femaleNum;
    }

    public Integer getGenderOtherNum() {
        return genderOtherNum;
    }

    public void setGenderOtherNum(Integer genderOtherNum) {
        this.genderOtherNum = genderOtherNum;
    }

    public Integer getOnlineAllNum() {
        return onlineAllNum;
    }

    public void setOnlineAllNum(Integer onlineAllNum) {
        this.onlineAllNum = onlineAllNum;
    }

    public Integer getOnlineMaleNum() {
        return onlineMaleNum;
    }

    public void setOnlineMaleNum(Integer onlineMaleNum) {
        this.onlineMaleNum = onlineMaleNum;
    }

    public Integer getOnlineFemaleNum() {
        return onlineFemaleNum;
    }

    public void setOnlineFemaleNum(Integer onlineFemaleNum) {
        this.onlineFemaleNum = onlineFemaleNum;
    }

    public Integer getOnlineGenderOtherNum() {
        return onlineGenderOtherNum;
    }

    public void setOnlineGenderOtherNum(Integer onlineGenderOtherNum) {
        this.onlineGenderOtherNum = onlineGenderOtherNum;
    }

    public com.feihua.framework.statistic.api.ApiStatisticUserClientCountHistoryPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.statistic.api.ApiStatisticUserClientCountHistoryPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clientId=").append(clientId);
        sb.append(", clientCode=").append(clientCode);
        sb.append(", clientName=").append(clientName);
        sb.append(", batchNo=").append(batchNo);
        sb.append(", allNum=").append(allNum);
        sb.append(", maleNum=").append(maleNum);
        sb.append(", femaleNum=").append(femaleNum);
        sb.append(", genderOtherNum=").append(genderOtherNum);
        sb.append(", onlineAllNum=").append(onlineAllNum);
        sb.append(", onlineMaleNum=").append(onlineMaleNum);
        sb.append(", onlineFemaleNum=").append(onlineFemaleNum);
        sb.append(", onlineGenderOtherNum=").append(onlineGenderOtherNum);
        sb.append("]");
        return sb.toString();
    }
}