package com.feihua.starter.service.mapper;

import com.feihua.starter.service.modules.leave.dto.SearchLeavesConditionDto;
import com.feihua.starter.service.modules.leave.po.OaLeavePo;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-04-11 14:57:50
 */
public interface OaLeavePoMapper extends feihua.jdbc.api.dao.CrudDao<OaLeavePo, String> {

    List<OaLeavePo> searchLeavesDsf(SearchLeavesConditionDto leavesConditionDto);
}