package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.role.dto.SearchRolesConditionDsfDto;
import com.feihua.framework.base.modules.role.dto.SearchRolesConditionDto;
import com.feihua.framework.base.modules.role.po.BaseRolePo;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2017-11-18 17:51:13
 */
public interface BaseRolePoMapper extends feihua.jdbc.api.dao.CrudDao<BaseRolePo, String> {
    /**
     * 搜索角色
     * @param dto
     * @return
     */
    public List<BaseRolePo> searchRolesDsf(SearchRolesConditionDsfDto dto);
}