package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.message.po.BaseMessageTemplatePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-29 20:18:23
 */
public interface BaseMessageTemplatePoMapper extends feihua.jdbc.api.dao.CrudDao<BaseMessageTemplatePo, String> {
    java.util.List<BaseMessageTemplatePo> searchBaseMessageTemplates(com.feihua.framework.base.modules.message.dto.SearchBaseMessageTemplatesConditionDto dto);
}