package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.calendar.po.BaseCalendarExtendPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-24 15:48:18
 */
public interface BaseCalendarExtendPoMapper extends feihua.jdbc.api.dao.CrudDao<BaseCalendarExtendPo, String> {
    java.util.List<BaseCalendarExtendPo> searchBaseCalendarExtends(com.feihua.framework.base.modules.calendar.dto.SearchBaseCalendarExtendsConditionDto dto);
}