package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.message.po.BaseMessageUserStatePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-29 20:28:33
 */
public interface BaseMessageUserStatePoMapper extends feihua.jdbc.api.dao.CrudDao<BaseMessageUserStatePo, String> {
}