package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.postjob.po.BasePostJobDataScopeDefinePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-14 11:33:17
 */
public interface BasePostJobDataScopeDefinePoMapper extends feihua.jdbc.api.dao.CrudDao<BasePostJobDataScopeDefinePo, String> {
}