package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.postjob.po.BasePostDataScopeDefinePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-14 11:32:30
 */
public interface BasePostDataScopeDefinePoMapper extends feihua.jdbc.api.dao.CrudDao<BasePostDataScopeDefinePo, String> {
}