package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.datascope.dto.SearchDataScopesConditionDsfDto;
import com.feihua.framework.base.modules.datascope.po.BaseDataScopePo;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-01-09 13:35:54
 */
public interface BaseDataScopePoMapper extends feihua.jdbc.api.dao.CrudDao<BaseDataScopePo, String> {
    /**
     * 模糊搜索数据范围
     * @param conditionDto
     * @return
     */
    List<BaseDataScopePo> searchDataScopes(SearchDataScopesConditionDsfDto conditionDto);
}