package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.rel.po.BaseUserUserGroupRelPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-20 13:37:34
 */
public interface BaseUserUserGroupRelPoMapper extends feihua.jdbc.api.dao.CrudDao<BaseUserUserGroupRelPo, String> {
}