package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.dict.po.BaseDictDataScopeDefinePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-03-26 12:58:35
 */
public interface BaseDictDataScopeDefinePoMapper extends feihua.jdbc.api.dao.CrudDao<BaseDictDataScopeDefinePo, String> {
}