package com.feihua.framework.base.mapper;

import com.feihua.framework.base.modules.group.po.BaseUserGroupDataScopeDefinePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-20 13:26:41
 */
public interface BaseUserGroupDataScopeDefinePoMapper extends feihua.jdbc.api.dao.CrudDao<BaseUserGroupDataScopeDefinePo, String> {
}