package com.feihua.framework.base.modules.loginclient.dto;

import feihua.jdbc.api.pojo.BaseConditionDto;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_login_client
 *
 * @mbg.generated 2019-04-04 11:42:32
*/
public class SearchBaseLoginClientsConditionDto extends BaseConditionDto {

    private String code;

    private String name;

    private String type;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}