package com.feihua.framework.base.modules.group.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-20 14:17:18
 * Database Table Remarks:
 *   用户分组表
 *
 * This class corresponds to the database table base_user_group
 * @mbg.generated do_not_delete_during_merge 2019-06-20 14:17:18
*/
public class BaseUserGroupPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_group.NAME
     *
     * @mbg.generated 2019-06-20 14:17:18
     */
    private String name;

    /**
     * Database Column Remarks:
     *   编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_group.CODE
     *
     * @mbg.generated 2019-06-20 14:17:18
     */
    private String code;

    /**
     * Database Column Remarks:
     *   类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_group.TYPE
     *
     * @mbg.generated 2019-06-20 14:17:18
     */
    private String type;

    /**
     * Database Column Remarks:
     *   是否 公共，Y=是，N=否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_group.IS_PUBLIC
     *
     * @mbg.generated 2019-06-20 14:17:18
     */
    private String isPublic;

    /**
     * Database Column Remarks:
     *   是否禁用，N=未禁用；Y=已禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_group.DISABLED
     *
     * @mbg.generated 2019-06-20 14:17:18
     */
    private String disabled;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(String isPublic) {
        this.isPublic = isPublic;
    }

    public String getDisabled() {
        return disabled;
    }

    public void setDisabled(String disabled) {
        this.disabled = disabled;
    }

    public com.feihua.framework.base.modules.group.api.ApiBaseUserGroupPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.framework.base.modules.group.api.ApiBaseUserGroupPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", type=").append(type);
        sb.append(", isPublic=").append(isPublic);
        sb.append(", disabled=").append(disabled);
        sb.append("]");
        return sb.toString();
    }
}