package com.feihua.framework.statistic.mapper;

import com.feihua.framework.statistic.po.StatisticRecordPageSharePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-28 14:00:30
 */
public interface StatisticRecordPageSharePoMapper extends feihua.jdbc.api.dao.CrudDao<StatisticRecordPageSharePo, String> {
    java.util.List<StatisticRecordPageSharePo> searchStatisticRecordPageShares(com.feihua.framework.statistic.dto.SearchStatisticRecordPageSharesConditionDto dto);
}