package com.feihua.framework.statistic.mapper;

import com.feihua.framework.statistic.po.StatisticUserAreaCountPo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-23 09:21:58
 */
public interface StatisticUserAreaCountPoMapper extends feihua.jdbc.api.dao.CrudDao<StatisticUserAreaCountPo, String> {
}