package com.feihua.wechat.publicplatform.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-08-17 14:59:27
 *
 * This class corresponds to the database table weixin_menu
 * @mbg.generated do_not_delete_during_merge 2018-08-17 14:59:27
*/
public class WeixinMenuPo extends feihua.jdbc.api.pojo.BaseTreePo<String> {
    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.NAME
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private String name;

    /**
     * Database Column Remarks:
     *   KEY
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.KEY
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private String key;

    /**
     * Database Column Remarks:
     *   类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.TYPE
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private String type;

    /**
     * Database Column Remarks:
     *   连接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.URL
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private String url;

    /**
     * Database Column Remarks:
     *   调用新增永久素材接口返回的合法media_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.MEDIA_ID
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private String mediaId;

    /**
     * Database Column Remarks:
     *   小程序的appid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.APPID
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private String appid;

    /**
     * Database Column Remarks:
     *   小程序的页面路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.PAGEPATH
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private String pagepath;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.SEQUENCE
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private Integer sequence;

    /**
     * Database Column Remarks:
     *   字典，标识哪一个公众号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu.WHICH
     *
     * @mbg.generated 2018-08-17 14:59:27
     */
    private String which;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getMediaId() {
        return mediaId;
    }

    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }

    public String getAppid() {
        return appid;
    }

    public void setAppid(String appid) {
        this.appid = appid;
    }

    public String getPagepath() {
        return pagepath;
    }

    public void setPagepath(String pagepath) {
        this.pagepath = pagepath;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getWhich() {
        return which;
    }

    public void setWhich(String which) {
        this.which = which;
    }

    public com.feihua.wechat.publicplatform.api.ApiWeixinMenuPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.feihua.wechat.publicplatform.api.ApiWeixinMenuPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", key=").append(key);
        sb.append(", type=").append(type);
        sb.append(", url=").append(url);
        sb.append(", mediaId=").append(mediaId);
        sb.append(", appid=").append(appid);
        sb.append(", pagepath=").append(pagepath);
        sb.append(", sequence=").append(sequence);
        sb.append(", which=").append(which);
        sb.append("]");
        return sb.toString();
    }
}