package com.feihua.framework.base.impl;

import com.feihua.framework.base.modules.postjob.api.ApiBasePostPoService;
import com.feihua.framework.base.modules.postjob.dto.BasePostDto;
import com.feihua.framework.base.modules.postjob.po.BasePostPo;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;

import feihua.jdbc.api.service.impl.ApiBaseTreeServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-06 11:05:12
 */
@Service
public class ApiBasePostPoServiceImpl extends ApiBaseTreeServiceImpl<BasePostPo, BasePostDto, String> implements ApiBasePostPoService {
    @Autowired
    com.feihua.framework.base.mapper.BasePostPoMapper BasePostPoMapper;

    public ApiBasePostPoServiceImpl() {
        super(BasePostDto.class);
    }

    @Override
    public PageResultDto<BasePostDto> searchBasePostsDsf(com.feihua.framework.base.modules.postjob.dto.SearchBasePostsConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.feihua.framework.base.modules.postjob.dto.BasePostDto> list = this.wrapDtos(BasePostPoMapper.searchBasePosts(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }

    @Override
    public BasePostDto wrapDto(BasePostPo po) {
        if (po == null) { return null; }
        BasePostDto dto = new BasePostDto();
        dto.setId(po.getId());
        dto.setName(po.getName());
        dto.setCode(po.getCode());
        dto.setType(po.getType());
        dto.setPostJobId(po.getPostJobId());
        dto.setDisabled(po.getDisabled());
        dto.setLevel(po.getLevel());
        dto.setParentId(po.getParentId());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}