package com.feihua.framework.base.impl;

import com.feihua.exception.BaseException;
import com.feihua.exception.DataConflictException;
import com.feihua.framework.base.modules.datascope.api.ApiBaseDataScopeService;
import com.feihua.framework.base.modules.postjob.api.ApiBasePostPoService;
import com.feihua.framework.base.modules.postjob.po.BasePostPo;
import com.feihua.framework.base.modules.rel.api.ApiBasePostRoleRelPoService;
import com.feihua.framework.base.modules.rel.dto.BasePostRoleRelDto;
import com.feihua.framework.base.modules.role.api.ApiBaseRolePoService;
import com.feihua.framework.base.modules.role.po.BaseRolePo;
import com.feihua.framework.constants.DictEnum;
import com.feihua.framework.base.modules.office.api.ApiBaseOfficeDataScopeDefinePoService;
import com.feihua.framework.base.modules.office.api.ApiBaseOfficeDataScopeDefineSelfPoService;
import com.feihua.framework.base.modules.office.dto.BaseOfficeDataScopeDefineDto;
import com.feihua.framework.base.modules.office.dto.OfficeDataScopeParamDto;
import com.feihua.framework.base.modules.office.po.BaseOfficeDataScopeDefinePo;
import com.feihua.framework.base.modules.rel.api.ApiBaseRoleDataScopeRelPoService;
import com.feihua.framework.base.modules.rel.api.ApiBaseUserDataScopeRelPoService;
import com.feihua.framework.base.modules.rel.dto.BaseRoleDataScopeRelDto;
import com.feihua.framework.base.modules.rel.dto.BaseUserDataScopeRelDto;
import feihua.jdbc.api.pojo.BasePo;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-03-19 18:39:44
 */
@Service
public class ApiBaseOfficeDataScopeDefinePoServiceImpl extends ApiBaseServiceImpl<BaseOfficeDataScopeDefinePo, BaseOfficeDataScopeDefineDto, String> implements ApiBaseOfficeDataScopeDefinePoService ,ApiBaseDataScopeService<BaseOfficeDataScopeDefineDto> {

    public ApiBaseOfficeDataScopeDefinePoServiceImpl() {
        super(BaseOfficeDataScopeDefineDto.class);
    }

    @Autowired
    private ApiBaseOfficeDataScopeDefineSelfPoService apiBaseOfficeDataScopeDefineSelfPoService;
    @Autowired
    private ApiBaseUserDataScopeRelPoService apiBaseUserDataScopeRelPoService;
    @Autowired
    private ApiBaseRoleDataScopeRelPoService apiBaseRoleDataScopeRelPoService;
    @Autowired
    private ApiBasePostPoService apiBasePostPoService;
    @Autowired
    private ApiBasePostRoleRelPoService apiBasePostRoleRelPoService;
    @Autowired
    private ApiBaseRolePoService apiBaseRolePoService;



    @Transactional( propagation = Propagation.SUPPORTS, readOnly = true )
    @Override
    public BaseOfficeDataScopeDefineDto selectByDataScopeId(String dataScopeId) {
        if(StringUtils.isEmpty(dataScopeId)) return null;
        BaseOfficeDataScopeDefinePo condition = new BaseOfficeDataScopeDefinePo();
        condition.setDataScopeId(dataScopeId);
        condition.setDelFlag(BasePo.YesNo.N.name());
        return this.selectOne(condition);
    }
    @Transactional(rollbackFor = Exception.class)
    @Override
    public BaseOfficeDataScopeDefineDto setOfficeDataScope(OfficeDataScopeParamDto officeDataScope) {
        // 先查询是否已经设置
        BaseOfficeDataScopeDefinePo condition = new BaseOfficeDataScopeDefinePo();
        condition.setDataScopeId(officeDataScope.getDataScopeId());
        condition.setDelFlag(BasePo.YesNo.N.name());
        BaseOfficeDataScopeDefinePo dbOfficeDataScopeDefinePo = this.selectOneSimple(condition);
        // 如果没有设置
        if(dbOfficeDataScopeDefinePo == null){
            dbOfficeDataScopeDefinePo = new BaseOfficeDataScopeDefinePo();
            dbOfficeDataScopeDefinePo.setDataScopeId(officeDataScope.getDataScopeId());
            dbOfficeDataScopeDefinePo.setType(officeDataScope.getType());
            dbOfficeDataScopeDefinePo = this.preInsert(dbOfficeDataScopeDefinePo,officeDataScope.getCurrentUserId());
            dbOfficeDataScopeDefinePo = this.insertSimple(dbOfficeDataScopeDefinePo);
            if(dbOfficeDataScopeDefinePo == null){
                throw new BaseException("add officeDataScopeDefine return null","E500");
            }
            // 如果是自定义且自定义勾选不为空，添加自定义数据
            if(DictEnum.OfficeDataScope.self.name().equals(officeDataScope.getType())
                    && officeDataScope.getOfficeIds() != null && !officeDataScope.getOfficeIds().isEmpty()){
                int r = apiBaseOfficeDataScopeDefineSelfPoService.insertOfficeSelf(officeDataScope.getOfficeIds(),dbOfficeDataScopeDefinePo.getId(),officeDataScope.getCurrentUserId());
                // 如果失败
                if(r <= 0){
                    throw new BaseException("add officeDataScopeDefineSelf return " + r,"E500");
                }
            }
            return this.wrapDto(dbOfficeDataScopeDefinePo);
        }
        // 如果已经设置
        else{
            dbOfficeDataScopeDefinePo.setType(officeDataScope.getType());
            dbOfficeDataScopeDefinePo = this.preUpdate(dbOfficeDataScopeDefinePo,officeDataScope.getCurrentUserId());
            // 这里没有用乐观锁
            int updateR = this.updateByPrimaryKeySelective(dbOfficeDataScopeDefinePo);
            // 更新失败
            if(updateR <= 0){
                throw new BaseException("update officeDataScopeDefine return " + updateR,"E500");
            }
            // 更新成功后
            else{
                // 先删除掉以前配置的自定义勾选
                int deleteR = apiBaseOfficeDataScopeDefineSelfPoService.deleteOfficeSelfByOfficeDataScopeDefineId(dbOfficeDataScopeDefinePo.getId(),officeDataScope.getCurrentUserId());

                if(DictEnum.OfficeDataScope.self.name().equals(officeDataScope.getType())
                        && officeDataScope.getOfficeIds() != null && !officeDataScope.getOfficeIds().isEmpty()){
                    int insertR = apiBaseOfficeDataScopeDefineSelfPoService.insertOfficeSelf(officeDataScope.getOfficeIds(),dbOfficeDataScopeDefinePo.getId(),officeDataScope.getCurrentUserId());
                    // 如果失败
                    if(insertR <= 0){
                        throw new BaseException("add officeDataScopeDefineSelf return " + insertR,"E500");
                    }
                }
            }
            return this.wrapDto(dbOfficeDataScopeDefinePo);
        }
    }
    @Transactional( propagation = Propagation.SUPPORTS, readOnly = true )
    @Override
    public BaseOfficeDataScopeDefineDto selectDataScopeDefineByUserId(String userId, String roleId, String postId) {

        BaseUserDataScopeRelDto userDataScopeRelDto = apiBaseUserDataScopeRelPoService.selectByUserId(userId);
        // 用户设置了数据范围，以该数据范围优先
        if(userDataScopeRelDto != null){
            return this.selectByDataScopeId(userDataScopeRelDto.getDataScopeId());
        }
        // 取角色设置的数据范围
        BaseRolePo rolePo = apiBaseRolePoService.selectByPrimaryKeySimple(roleId,false);
        if (rolePo != null && !BasePo.YesNo.Y.name().equals(rolePo.getDisabled())) {
            BaseRoleDataScopeRelDto roleDataScopeRelDto = apiBaseRoleDataScopeRelPoService.selectByRoleId(roleId);
            if(roleDataScopeRelDto != null){
                BaseOfficeDataScopeDefineDto defineDto = this.selectByDataScopeId(roleDataScopeRelDto.getDataScopeId());
                return defineDto;
            }
        }

        // 取岗位绑定的角色设置的数据范围
        BasePostPo postPo = apiBasePostPoService.selectByPrimaryKeySimple(postId,false);
        if (postPo != null && !BasePo.YesNo.Y.name().equals(postPo.getDisabled())) {
            BasePostRoleRelDto postRoleRelDto = apiBasePostRoleRelPoService.selectByPostId(postId);
            if (postRoleRelDto != null) {
                BaseRoleDataScopeRelDto roleDataScopeRelDto = apiBaseRoleDataScopeRelPoService.selectByRoleId(postRoleRelDto.getRoleId());
                if(roleDataScopeRelDto != null){
                    BaseOfficeDataScopeDefineDto defineDto = this.selectByDataScopeId(roleDataScopeRelDto.getDataScopeId());
                    return defineDto;
                }
            }
        }
        return null;
    }

    @Override
    public boolean isAllData(BaseOfficeDataScopeDefineDto dataScopeDefine) {
        if (dataScopeDefine != null && DictEnum.OfficeDataScope.all.name().equals(dataScopeDefine.getType())) {
            return true;
        }
        return false;
    }

    @Override
    public BaseOfficeDataScopeDefineDto wrapDto(BaseOfficeDataScopeDefinePo po) {
        if (po == null) {
            return null;
        }
        BaseOfficeDataScopeDefineDto officeDataScopeDefineDto = new BaseOfficeDataScopeDefineDto();
        officeDataScopeDefineDto.setDataScopeId(po.getDataScopeId());
        officeDataScopeDefineDto.setDataOfficeId(po.getDataOfficeId());
        officeDataScopeDefineDto.setDataType(po.getDataType());
        officeDataScopeDefineDto.setDataAreaId(po.getDataAreaId());
        officeDataScopeDefineDto.setId(po.getId());
        officeDataScopeDefineDto.setUpdateAt(po.getUpdateAt());
        officeDataScopeDefineDto.setType(po.getType());
        officeDataScopeDefineDto.setDataUserId(po.getDataUserId());
        return officeDataScopeDefineDto;
    }
}