package com.feihua.framework.base.impl;

import com.feihua.framework.base.modules.datascope.api.ApiBaseDataScopeService;
import com.feihua.framework.constants.DictEnum;
import com.feihua.framework.base.modules.function.api.ApiBaseFunctionResourceDataScopeDefineSelfPoService;
import com.feihua.framework.base.modules.function.api.ApiBaseFunctionResourcePoService;
import com.feihua.framework.base.modules.function.dto.*;
import com.feihua.framework.base.mapper.BaseFunctionResourcePoMapper;
import com.feihua.framework.base.modules.function.po.BaseFunctionResourcePo;
import com.feihua.utils.string.StringUtils;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.PageAndOrderbyParamDto;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseTreeServiceImpl;
import org.apache.commons.collections.CollectionUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-01-19 20:14:24
 */
@Service
public class ApiBaseFunctionResourcePoServiceImpl extends ApiBaseTreeServiceImpl<BaseFunctionResourcePo, BaseFunctionResourceDto, String> implements ApiBaseFunctionResourcePoService {

    public ApiBaseFunctionResourcePoServiceImpl() {
        super(BaseFunctionResourceDto.class);
    }

    @Autowired
    private ApiBaseDataScopeService<BaseFunctionResourceDataScopeDefineDto> apiBaseFunctionDataScopeService;
    @Autowired
    private BaseFunctionResourcePoMapper baseFunctionResourcePoMapper;
    @Autowired
    private ApiBaseFunctionResourceDataScopeDefineSelfPoService apiBaseFunctionResourceDataScopeDefineSelfPoService;

    @Transactional( propagation = Propagation.SUPPORTS, readOnly = true )
    @Override
    public PageResultDto<BaseFunctionResourceDto> searchFunctionResourcesDsf(SearchFunctionResourcesConditionDto dto, PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        BaseFunctionResourceDataScopeDefineDto functionResourceDataScopeDefineDto = apiBaseFunctionDataScopeService.selectDataScopeDefineByUserId(dto.getCurrentUserId(),dto.getCurrentRoleId(),dto.getCurrentPostId());
        if (functionResourceDataScopeDefineDto == null || StringUtils.isEmpty(functionResourceDataScopeDefineDto.getType()) || StringUtils.isEmpty(functionResourceDataScopeDefineDto.getType())) {
            return new PageResultDto();
        }
        String type = functionResourceDataScopeDefineDto.getType();

        SearchFunctionResourcesConditionDsfDto searchFunctionResourcesConditionDsfDto = new SearchFunctionResourcesConditionDsfDto();
        searchFunctionResourcesConditionDsfDto.setName(dto.getName());
        searchFunctionResourcesConditionDsfDto.setIsShow(dto.getIsShow());
        searchFunctionResourcesConditionDsfDto.setType(dto.getType());
        searchFunctionResourcesConditionDsfDto.setParentId(dto.getParentId());
        // 如果是所有数据
        if(DictEnum.FunctionResourceDataScope.all.name().equals(type)){
            Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
            List<BaseFunctionResourceDto> list = this.wrapDtos(baseFunctionResourcePoMapper.searchFunctionResources(searchFunctionResourcesConditionDsfDto));
            return new PageResultDto(list, this.wrapPage(p));
        }

        // 如果是自定义
        if(DictEnum.FunctionResourceDataScope.self.name().equals(type)){
            List<BaseFunctionResourceDataScopeDefineSelfDto> functionResourceDataScopeDefineSelfDtos = apiBaseFunctionResourceDataScopeDefineSelfPoService.selectByFunctionResourceDataScopeDefineId(functionResourceDataScopeDefineDto.getId());
            if(CollectionUtils.isEmpty(functionResourceDataScopeDefineSelfDtos)){
                return new PageResultDto();
            }
            StringBuffer sb = new StringBuffer(" and ( 1 != 1");
            for (BaseFunctionResourceDataScopeDefineSelfDto functionResourceDataScopeDefineSelfDto : functionResourceDataScopeDefineSelfDtos) {
                sb.append(" or id = '").append(functionResourceDataScopeDefineSelfDto.getFunctionResourceId()).append("'");
            }
            sb.append(")");
            Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
            searchFunctionResourcesConditionDsfDto.setSelfCondition(sb.toString());
            List<BaseFunctionResourceDto> list = this.wrapDtos(baseFunctionResourcePoMapper.searchFunctionResources(searchFunctionResourcesConditionDsfDto));
            return new PageResultDto(list, this.wrapPage(p));
        }

        return new PageResultDto();
    }

    @Override
    public BaseFunctionResourceDto wrapDto(BaseFunctionResourcePo po) {
        if (po == null) {
            return null;
        }
        BaseFunctionResourceDto baseFunctionResourceDto = new BaseFunctionResourceDto();
        baseFunctionResourceDto.setName(po.getName());
        baseFunctionResourceDto.setPermissions(po.getPermissions());
        baseFunctionResourceDto.setDataOfficeId(po.getDataOfficeId());
        baseFunctionResourceDto.setDataAreaId(po.getDataAreaId());
        baseFunctionResourceDto.setSequence(po.getSequence());
        baseFunctionResourceDto.setDataUserId(po.getDataUserId());
        baseFunctionResourceDto.setType(po.getType());
        baseFunctionResourceDto.setLevel(po.getLevel());
        baseFunctionResourceDto.setDataType(po.getDataType());
        baseFunctionResourceDto.setUpdateAt(po.getUpdateAt());
        baseFunctionResourceDto.setIsShow(po.getIsShow());
        baseFunctionResourceDto.setIcon(po.getIcon());
        baseFunctionResourceDto.setUrl(po.getUrl());
        baseFunctionResourceDto.setParentId(po.getParentId());
        baseFunctionResourceDto.setId(po.getId());
        return baseFunctionResourceDto;
    }
}