package com.feihua.framework.base.impl;

import com.feihua.framework.base.modules.message.api.ApiBaseMessageUserStatePoService;
import com.feihua.framework.base.modules.message.dto.BaseMessageTemplateDto;
import com.feihua.framework.base.modules.message.dto.BaseMessageUserStateDto;
import com.feihua.framework.base.modules.message.po.BaseMessageUserStatePo;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.BasePo;
import feihua.jdbc.api.pojo.PageAndOrderbyParamDto;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-29 20:28:33
 */
@Service
public class ApiBaseMessageUserStatePoServiceImpl extends ApiBaseServiceImpl<BaseMessageUserStatePo, BaseMessageUserStateDto, String> implements ApiBaseMessageUserStatePoService {
    @Autowired
    com.feihua.framework.base.mapper.BaseMessageUserStatePoMapper BaseMessageUserStatePoMapper;

    public ApiBaseMessageUserStatePoServiceImpl() {
        super(BaseMessageUserStateDto.class);
    }

    @Override
    public PageResultDto<BaseMessageUserStateDto> viewReadPeople(String messageId,String isRead, PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        BaseMessageUserStatePo baseMessageUserStatePo = new BaseMessageUserStatePo();
        baseMessageUserStatePo.setMessageId(messageId);
        baseMessageUserStatePo.setDelFlag(BasePo.YesNo.N.name());
        List<BaseMessageUserStateDto> list = this.selectList(baseMessageUserStatePo);
        return new PageResultDto(list, this.wrapPage(p));
    }
}