package com.feihua.framework.base.impl;

import com.feihua.framework.base.modules.message.api.ApiBaseMessagePoService;
import com.feihua.framework.base.modules.message.dto.BaseMessageDto;
import com.feihua.framework.base.modules.message.dto.BaseMessageSendParamsDto;
import com.feihua.framework.base.modules.message.po.BaseMessagePo;
import com.github.pagehelper.Page;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-29 19:58:54
 */
@Service
public class ApiBaseMessagePoServiceImpl extends ApiBaseServiceImpl<BaseMessagePo, BaseMessageDto, String> implements ApiBaseMessagePoService {
    @Autowired
    com.feihua.framework.base.mapper.BaseMessagePoMapper BaseMessagePoMapper;

    public ApiBaseMessagePoServiceImpl() {
        super(BaseMessageDto.class);
    }

    @Override
    public PageResultDto<BaseMessageDto> searchBaseMessagesDsf(com.feihua.framework.base.modules.message.dto.SearchBaseMessagesConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.feihua.framework.base.modules.message.dto.BaseMessageDto> list = this.wrapDtos(BaseMessagePoMapper.searchBaseMessages(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }
    @Transactional(rollbackFor = Exception.class)
    @Override
    public void messageSend(BaseMessageSendParamsDto dto) {
        BaseMessagePo baseMessagePo = this.selectByPrimaryKeySimple(dto.getMessageId());
        if (baseMessagePo != null) {

        }
    }
}