package com.feihua.framework.base.modules.loginclient.api;

import com.feihua.framework.base.modules.loginclient.dto.BaseLoginClientChannelBindDto;
import com.feihua.framework.base.modules.loginclient.po.BaseLoginClientChannelBindPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-04-04 17:36:52
 */
public interface ApiBaseLoginClientChannelBindPoService extends feihua.jdbc.api.service.ApiBaseService<BaseLoginClientChannelBindPo, BaseLoginClientChannelBindDto, String> {
}