package com.feihua.framework.message.api;

import com.feihua.framework.message.dto.BaseMessageSendDto;
import com.feihua.framework.message.po.BaseMessageSendPo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-07 14:28:52
 */
public interface ApiBaseMessageSendPoService extends feihua.jdbc.api.service.ApiBaseService<BaseMessageSendPo, BaseMessageSendDto, String> {
}