package com.feihua.framework.message.api;

import com.feihua.framework.message.dto.BaseMessageTemplateDto;
import com.feihua.framework.message.po.BaseMessageTemplatePo;
import com.feihua.framework.message.dto.SearchBaseMessageTemplatesConditionDto;
import feihua.jdbc.api.pojo.PageResultDto;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-10-29 20:18:23
 */
public interface ApiBaseMessageTemplatePoService extends feihua.jdbc.api.service.ApiBaseService<BaseMessageTemplatePo, BaseMessageTemplateDto, String> {
    PageResultDto<BaseMessageTemplateDto> searchBaseMessageTemplatesDsf(SearchBaseMessageTemplatesConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto);

    /**
     * 根据模板查询编码
     * @param code
     * @return
     */
    BaseMessageTemplatePo selectByTemplateCode(String code);
}